[OFN-9870] Correct error message for differing variant_unit_name for same product in import
openfoodfoundation/openfoodnetwork pull request #10174
Opened 2022-12-20 01:46 UTC by ijdershem

#### What? Why?

- Closes #9870 

- When importing products, it is required that any two products with the same name have the same value for `variant_unit_name`. An error is thrown if `variant_unit_name` differs between products with the same name, however, the current error message for this case: "Variant_unit_name cannot be updated on existing products via product import" does not accurately reflect the cause of the error.

- This updates the error message to "Variant_unit_name must be the same for products with the same name." which accurately identifies the source of the error.

#### What should we test?

- Visit the product import page
- Upload a product_list template that contains two products with the same name, but differing `variant_unit_name` values
> - https://github.com/openfoodfoundation/openfoodnetwork/issues/9870 includes a 'Steps to Reproduce' section with a malformed .csv example that can be used to test
- Ensure that the error message for `variant_unit_name` correctly reads: "Variant_unit_name must be the same for products with the same name."
- Attached is a screenshot of how the error message should display

![image](https://user-images.githubusercontent.com/25915763/208561775-6c9ed024-b309-409c-9a3f-c372cdadb771.png)

#### Release notes

Changelog Category: User facing changes

2022-12-20 09:17 UTC, jibees requested changes
Only one trailing space that should be removed, other than that, it's ok. 

Thanks a lot @ijdershem ! 🙏

2022-12-20 16:58 UTC, jibees approved these changes
👌

2022-12-22 00:04 UTC, filipefurtad0 commented
Hey @ijdershem , welcome :tada: 

I've verified the error message before and after this PR, we can see this is working correctly now on my local **test environment**:

**Before this PR**

- Inventory import
![image](https://user-images.githubusercontent.com/49817236/209024546-157f287a-de25-4ac5-9989-6d51845cf41e.png)

- Product import
![image](https://user-images.githubusercontent.com/49817236/209024652-840c356a-a9cf-4185-aa09-906d9f8bc01d.png)

**After this PR**

I've added a spec [here](https://github.com/openfoodfoundation/openfoodnetwork/pull/10188) (still a draft), to cover these changes, and ran it on top of your PR. We can see that the correct error messages are now displayed to the user:

- Inventory import
![image](https://user-images.githubusercontent.com/49817236/209025420-4ca0787c-687c-43a5-bfe7-adfc5c8f3054.png)

- Product import
![image](https://user-images.githubusercontent.com/49817236/209025673-551db730-f9b7-4deb-8f99-b6ce65492296.png)

I'm moving this to ready-to-go, seems to addresses the issue correctly. I'll have a quick test on the staging server before merging.

Thank you so much :pray:

2022-12-22 11:20 UTC, filipefurtad0 commented
Checked in staging as well:

Product import:

![image](https://user-images.githubusercontent.com/49817236/209123377-b32c80e0-6cda-4eea-a7e6-de596f01f5ad.png)

Inventory import:

![image](https://user-images.githubusercontent.com/49817236/209123178-a02a1412-4027-4160-a778-c72312489f8c.png)


Thanks again.
Merging!

2022-12-22 11:20 UTC, merged