Fix product description style render with ng-bind-html
openfoodfoundation/openfoodnetwork pull request #10267
Opened 2023-01-12 14:52 UTC by mgrigoriev8109

#### What? Why?

- Closes #10211

Resolved the issue of bold, italics, underline, links not properly rendering in the short product description thanks to implementation suggested by jibees. 

Didn't see any similar existing view-related tests in the spec file, so figured that was for a reason and didn't add in a test. If I should let me know, otherwise feature can be tested manually by the steps listed below.

#### What should we test?

- Log in as default user `ofn@example.com` / `ofn123` 
- Navigate to http://localhost:3000/admin/products/fuji-apple/edit and add a short description to fuji apples under the admin's product's options. Short description should include bold, italics, underline, and a link. 
- Navigate to a farm's shop which has that fruit in. So if editing fuji apples in Freddy's Farm, navigate to http://localhost:3000/freddy-s-farm-shop/shop
- The short description should look as follows, with the styles rendering properly for bold, italics, underline, and links.

![Screenshot from 2023-01-12 09-25-09](https://user-images.githubusercontent.com/43343880/212094883-e838de67-0962-43ad-93bf-8726423b17bd.png)

#### Release notes

Changelog Category: User facing changes

2023-01-13 07:45 UTC, jibees approved these changes
That's exatcly how I would have done. 
 
What about adding some specs? I'm thinking about `spec/system/consumer/shopping/shopping_spec.rb`. Would you like to do this?

2023-01-13 13:19 UTC, mgrigoriev8109 commented
Definitely @jibees !

2023-01-16 03:15 UTC, mkllnk requested changes
Great. Just a spec, please! :smile:

2023-01-19 19:56 UTC, closed without merging

2023-01-19 19:57 UTC, mgrigoriev8109 commented
Going to try to re-fork the main repo again to fix some issues I'm seeing.