Report deleted fees in Enterprise Fee Summary
openfoodfoundation/openfoodnetwork pull request #10442
Opened 2023-02-15 04:33 UTC by mkllnk

#### What? Why?

- Closes #10395 

When testing [background processing of reports](https://github.com/openfoodfoundation/openfoodnetwork/pull/10413), @drummer83 found several server errors. Some where due to the new background processing but one seemed to be a pre-existing bug.

The Enterprise Fee Summary report assumes that an SQL result row has a fee name when the adjustment came from an enterprise fee. This is true since we introduced [soft-deletion on enterprise fees](https://github.com/openfoodfoundation/openfoodnetwork/pull/6679). But fees deleted before January 2021 do not exist any more and we can't display their name, type or owner.

The old report didn't recognise adjustments from deleted enterprise fees and raised an error. I relaxed one condition in the fee type detection which means that no error is raised and they are displayed in the report with some empty fields.
![Screenshot from 2023-02-15 15-30-10](https://user-images.githubusercontent.com/3524483/218930827-078d05df-9f1a-4d10-b88a-8332917d67a5.png)

#### What should we test?

- Visit /admin/reports/enterprise_fee_summary on au-staging or uk-staging.
- Run the report without date restrictions.

#### Release notes

Changelog Category: User facing changes

The title of the pull request will be included in the release notes.

#### Dependencies

#### Documentation updates

2023-02-16 10:45 UTC, jibees approved these changes
Nice catch, excellent comment, thanks for that! 👌

2023-02-23 01:48 UTC, dacook requested changes
Great, a very practical fix. I think I would have spent too long looking for a root cause, and the fix would most likely be the same anyway. 

`±` I  noticed that `for_enterprise_fee?` is no longer needed, so we might as well remove it too.
Otherwise good to go

2023-02-23 23:46 UTC, dacook approved these changes

2023-02-26 18:27 UTC, drummer83 commented
Hi @mkllnk,

as you can see, the failing reports before this PR are now rendering well after the PR:

| | UK admin | UK super admin | AU admin | AU super admin |
| - | - | - | - | - |
| BEFORE | :heavy_check_mark: | :x: | :heavy_check_mark: | :x: |
| AFTER | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |

Thanks for this fix! :muscle: 
Merging! :tada:

2023-02-26 18:28 UTC, merged