Do not update `estimate_price` of a variant that is not available for the shop on OrderCycle update
openfoodfoundation/openfoodnetwork pull request #10514
Opened 2023-03-03 14:11 UTC by jibees

#### What? Why?
This is a tough one, I hope the solution is good. 
- Closes #9292

#### What should we test?

The setup I used to _reproduce_ (I hope...) the issue:
 - Having a closing OC with a schedule
<img width="1391" alt="Capture d’écran 2023-03-03 à 15 09 39" src="https://user-images.githubusercontent.com/296452/222741777-5e2bc866-de84-4664-8009-2899794b39af.png">

 - Adding product to this schedule (here `Garlic 200g`)
<img width="1243" alt="Capture d’écran 2023-03-03 à 15 10 11" src="https://user-images.githubusercontent.com/296452/222741913-001fe5ed-7187-47e1-b77f-bdbd504599bf.png">

- Delete this variant
- Try to update OC. _Before_ the PR, you should see an error message ; _After_ the PR, the OC must be edited with a success message.

#### Release notes

Changelog Category: User facing changes | Technical changes

The title of the pull request will be included in the release notes.

#### Dependencies

#### Documentation updates

2023-03-06 05:54 UTC, mkllnk requested changes
Great. Spec? :smile:

2023-03-06 16:07 UTC, jibees commented
> Great. Spec? 😄

:+1: Done with commit a9502abff6

2023-03-07 00:56 UTC, mkllnk approved these changes

2023-03-07 05:38 UTC, dacook approved these changes
Great fix.

2023-03-07 05:38 UTC, dacook commented on app/controllers/admin/order_cycles_controller.rb
> +          fee_calculator = OpenFoodNetwork::EnterpriseFeeCalculator.new(shop, order_cycle)
🙌

2023-03-08 14:44 UTC, drummer83 commented
Hi @jibees,
Thanks for this one!

## Test setup to reproduce the issue
- have a customer with a subscription (kunde2@k... @Konrad Producer Hub (Tax)
- have the order cycle closed in the past
- add a product to the subscription ($NaN is displayed as price) and save
- delete this variant from product list
- try to update the order cycle (change date, name, incoming/outgoing, etc.) 💥 
Error: Order could not be saved, but changes are actually saved.

## After the PR
- same steps as above
No error. Date, name, incoming/outgoing products etc. can be updated and changes are successfully saved. The screen is also showing the green confirmation at the bottom.

![image](https://user-images.githubusercontent.com/1790176/223743204-6ad9441f-554c-4b7d-b69e-c3241501f010.png)

This is just great! 🤗 
No regression was found! Merging! 🎉 

Thanks again!

2023-03-08 14:45 UTC, merged