Webpack, dev. env: Fix configuration export
openfoodfoundation/openfoodnetwork pull request #10631
Opened 2023-03-29 08:47 UTC by jibees

#### What? Why?
Since https://github.com/openfoodfoundation/openfoodnetwork/pull/10568 we changed a bit the configuration options for webpack in development environement. The PR was incomplete, since it does not export the right value. Change that. 

#### What should we test?
- Locally, remove `public/packs` folder
- Start your server (via `foreman start`) and check that after requesting a page, folder `public/packs` is not empty and you don't have any errors in your browser console

#### Release notes

Changelog Category: Technical changes

2023-03-29 22:37 UTC, dacook commented
Oh, sorry I missed that. In fact, apparently there is **[a lot](https://github.com/webpack/webpack-dev-server/blob/master/migration-v4.md)** of release notes that I missed.

2023-03-29 22:43 UTC, dacook approved these changes
Changes look good, although I have to admit I'm not familiar with webpack configuration.

Dev test also good (just some errors from missing active_storage images which I think is unrelated):
![Screen Shot 2023-03-30 at 9 35 57 am](https://user-images.githubusercontent.com/4188088/228684253-1832627e-e529-4610-b3d1-ce0a9fab4909.png)

2023-03-29 22:43 UTC, dacook commented on config/webpack/development.js
> +module.exports = config;
I see that we were exporting the original config instead of the changed config, so this change makes sense 👍

2023-03-30 12:18 UTC, jibees commented
Actually, this seems not solve the original issue: I can still observe the bug with the configuration. 
Steps to reproduce (?): 
 - `rm -rf public/packs`
 - `foreman start`
 - refresh browser
 - modify `app/webpacker/controllers/tom_select_controller.js` (I guess it's the same for all js files ...)
 - refresh the browser
 - Observe the 404 in the browser console:
```
GET http://localhost:3000/packs/packs/js/application-e08cb490b1e7d7ef4c24.js 404 (Not Found)
:3000/packs/css/darkswarm-028d6116.css:1
GET http://localhost:3000/packs/css/darkswarm-028d6116.css 404 (Not Found)
```
or in the rails console:
```
ActionController::RoutingError (No route matches [GET] "/packs/packs/js/application-9fbe5618e90966ec3586.js"):
```

2023-03-30 13:15 UTC, jibees commented
I spend a lot of time, trying to solve what's happening here, without any success ; actually I'm even not sure on how to reproduce the issue! I think it's great if we could start working on Rails Assets Management pipeline to remove webpack(er) and having a _up-to-date_ assets management system. 

_Note:_ from [V3 to V4 migrating guide](https://github.com/webpack/webpack-dev-server/blob/master/migration-v4.md) of webpack-dev-server they recommend to use webpack >= 5. 

> but we recommend using webpack >= v5.0.0

2023-04-02 06:10 UTC, abdellani commented
> Actually, this seems not solve the original issue: I can still observe the bug with the configuration. Steps to reproduce (?):
> 
> * `rm -rf public/packs`
> * `foreman start`
> * refresh browser
> * modify `app/webpacker/controllers/tom_select_controller.js` (I guess it's the same for all js files ...) ; to activate hotmodulereload
> * refresh the browser
> * Observe the 404 in the browser console:
> 
> ```
> GET http://localhost:3000/packs/packs/js/application-e08cb490b1e7d7ef4c24.js 404 (Not Found)
> :3000/packs/css/darkswarm-028d6116.css:1
> GET http://localhost:3000/packs/css/darkswarm-028d6116.css 404 (Not Found)
> ```
> 
> or in the rails console:
> 
> ```
> ActionController::RoutingError (No route matches [GET] "/packs/packs/js/application-9fbe5618e90966ec3586.js"):
> ```

Hi @jibees 
I followed the same steps but I didn't get any errors on the browser's console.

2023-04-03 06:24 UTC, jibees commented
Yep, you're right, this does not solve anything. Sorry, that's why this was back to `In Dev`

2023-04-03 08:15 UTC, jibees commented
- Remove `public/packs`
- Starts `./bin/webpack-dev-server`
Compiled with `ddf7a90f84980a3795b1` as hash, `manifest.json` file is created referencing (it's just an example):
```
"application": {
      "js": [
        "/packs/packs/js/application-ddf7a90f84980a3795b1.js"
      ],
```
with the hash `ddf7a90f84980a3795b1`. 
- Start the rails server
- Request a shopfront
- Webpack starts compiling (through the rails app) files with a different hash, but that's fine because `manifest.json` now reference that new hash:
File created:
```
public/packs/packs/js/application-18f09577984a69a22fe2.js
```
`manifest.json`:
```
    "application": {
      "js": [
        "/packs/packs/js/application-18f09577984a69a22fe2.js"
      ],
```
- Modify `app/webpacker/controllers/tom_select_controller.js` but without any modification. Hash is now `c82464ad1118ed74b959`, as read in the manifest.json file:
```
    "application": {
      "js": [
        "/packs/packs/js/application-c82464ad1118ed74b959.js"
      ],
```
No files are created with this hash since compilation has not started through webpack.
- Then request the shopfront: no webpack compilation is started, and requesting files fails because of that de-synchronization between `webpack-dev-server` and `webpack` hash
```
ActionController::RoutingError (No route matches [GET] "/packs/packs/js/application-c82464ad1118ed74b959.js"):
```
(`c82464ad1118ed74b959` is the hash in the `manifest.json` file, but no file had been created with that hash)


My (partial) conclusion is: there seems to have a de-synchronization between `webpack-dev-server` and `webpack` around that hash (between `manifest.json` and files that are actually created).

2023-04-03 22:54 UTC, mkllnk commented
> My (partial) conclusion is: there seems to have a de-synchronization between webpack-dev-server and webpack around that hash (between manifest.json and files that are actually created).

A hash is usually unique to some input. If you don't change the input then the hash stays the same. So it seems like webpack-dev-server has some changing input which webpack doesn't have. Does it somehow include some already compiled files again? Or is it including a timestamp even though it shouldn't? It could be a bug but these are just theories. I haven't looked into this.

Shall we just abandon webpack-dev-server? If we move to another tool, we won't have that feature anyway, right? It just means that Rails has to recompile with webpack on a new request after changing assets and the browser won't reload automatically.

2023-04-04 06:27 UTC, rioug commented
This causing issue for the docker environment as well. Just noting my observation so far :
- currently js files are generated in `public/packs/packs/js/` 
- the webpage is requesting js files from `packs/js` but with the wrong hash :confused: 

If I apply @jibees fix then webpack generate a `manifest.json` but nothing else :confused:

2023-04-04 12:42 UTC, jibees commented
thanks @rioug for spotting that. I was pretty sure that I already removed that _test_ in my commit, but indeed no. I tried with your suggested solution (which I think I already tested): it does not work for me as expected. I always have some `Routing errors` and de-synchronization between webpack, rails, ...

2023-04-06 00:44 UTC, rioug commented
I played around with this a little bit more with a docker setup. I can see webpack-dev-server recompiling file and updating `manifest.json` when a file is updated. But it doesn't trigger an auto reload. If I then refresh/load the page webpack will recompile (through the rails app) and pick up the change. 
We don't get the benefit of the webpack-dev-server then but at least it's not creating errors.

I realise this is not supper helpful ...

2023-04-06 08:17 UTC, jibees commented
> I can see webpack-dev-server recompiling file and updating manifest.json when a file is updated. But it doesn't trigger an auto reload. If I then refresh/load the page webpack will recompile (through the rails app) and pick up the change.

Same here (not using docker)

2023-04-30 23:46 UTC, rioug commented
Looks like the issue is coming from the upgrade of `webpack-dev-server` to 4.x  and should be fixed by : #10765

2023-05-02 06:39 UTC, rioug commented
I rebased and removed the minimum version as we are still on `webpack-dev-server` 3  it's not applicable to us.

2023-05-02 09:51 UTC, jibees commented
Thanks @rioug ! I've tested, and seems to work well. I think this is ready to be reviewed.

2023-05-03 01:24 UTC, dacook approved these changes
Thanks, I can see this is now just a one-line config change, which looks good to me. 

It looks like it has already been dev tested, but I'll give it another go.

✅ Looks good, I can see `public/packs` is created, and local server works. I see a couple of image load errors, but they are active_storage images and probably due to my local data.

✅ [Deployed to staging](https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/servers/au-staging/deploys/635), no console errors.

Ready to merge?

2023-05-03 01:48 UTC, mkllnk requested changes
I think that we are trying to fix a workaround which was only introduced by the incompatibility of webpacker versions. We should restore the original file:

```js
process.env.NODE_ENV = process.env.NODE_ENV || 'development'

const environment = require('./environment')

module.exports = environment.toWebpackConfig()
```

Investigating this I found that we are changing the filename generation to use `hash` instead of `contenthash`. But `contenthash` is recommended and in use by default. I guess that the now reverted version bump changed the naming which brought up this incompatibility. We can now use the default config again.

Sources:

* https://medium.com/@web_developer/hash-vs-chunkhash-vs-contenthash-e94d38a32208
* https://github.com/webpack/webpack.js.org/issues/2096

2023-05-03 08:06 UTC, jibees commented
@mkllnk 
You'r right. Will close this PR (too many comments) and open a new one to bring those changes. Thanks for your attention! 🙏

2023-05-03 08:06 UTC, closed without merging