Fix admin product variants form to close issues #10579 & Wishlist: 430
openfoodfoundation/openfoodnetwork pull request #10684
Opened 2023-04-11 15:31 UTC by MadisonBowron

#### What? Why?

- Closes #10579 
- (and wishlist issue 430)

- There was no error message when the user entered an invalid weight into the admin/product/edit/variant page. The form now matches the width, and height entries, where an error appears for non-numeric values, and those that do not fit the precision limit. 
- Changed precision limit for shipping weight for products with non-weight units to 3. (Wishlist item 430)

#### What should we test?
Test weight inputs as product unit, and as shipping weight on /admin/products/<product>/variants/<#>/edit page

- Visit /admin/products/<product>/variants/<#>/edit page.

#### Release notes

Changelog Category: User facing changes

Fix admin product variants form to close issues #10579 & #430

2023-04-14 05:06 UTC, mkllnk requested changes
Thank you for this. That's great. I noticed that you didn't add a test case for the issue of adding invalid input but it seems that Capybara doesn't allow us to enter invalid values. All good.

Could you remove those comments, please?

2023-04-17 02:11 UTC, mkllnk approved these changes

2023-04-17 05:34 UTC, rioug approved these changes
Looks good :+1:

2023-04-24 16:17 UTC, drummer83 commented
Hi @MadisonBowron,
Thank you for this pull request! I did some testing and here is what I found.

## Closing #10579 
- The weight input is nicely validated now. Only decimals are allowed. :heavy_check_mark: 
- There is immediate feedback if invalid input is provided (input field highlighted in red). :heavy_check_mark: 
- While invalid input is present no data will be stored when clicking 'Update'. :heavy_check_mark: 

https://user-images.githubusercontent.com/1790176/234052800-4c2a18f5-9de1-4969-9f26-42b49280e5d8.mp4

### Additional notes (out of scope for this PR)
- The weight input should allow and store three decimals. :arrow_right: 
- There is no error message and nothing gets saved when weight input is a negative decimal. :arrow_right: 

## Closing [wishlist #430](https://github.com/openfoodfoundation/wishlist/issues/430)
- The input is validated. Only decimals are allowed. :heavy_check_mark: 
- The input is now allowing three decimals. :heavy_check_mark: 
- After updating, the value is rounded to a decimal with two digits plus a zero in the third digit. :x:

https://user-images.githubusercontent.com/1790176/234053195-2bde36de-fd42-4c6c-9b4c-d9b869e7a4ba.mp4

## Conclusion
- This PR closes #10579. There is room for minor further improvevments which are out of scope here. I will open issues for those.
- I don't think we can close [wishlist #430](https://github.com/openfoodfoundation/wishlist/issues/430) because the third digit doesn't get saved to the database or at least it is not displayed after updating.
- There is improvement here and no regression, so I think we can merge and fix the remaining bits in a separate PR.

Thanks again for your contribution!
I'm merging the PR now! :partying_face:

2023-04-24 16:18 UTC, merged