Remove SessionCookieUpgrader from middleware
openfoodfoundation/openfoodnetwork pull request #10767
Opened 2023-04-28 13:04 UTC by Matt-Yorkley

#### What? Why?

This was a transitional bit of code to allow us to rename our session cookies without killing active sessions and logging users out. It was a tricky task but it's done it's job now, the transition happened smoothly, and it isn't currently doing anything useful. It can be removed from the middleware stack :+1: 

#### What should we test?

No test?

#### Release notes

Changelog Category: Technical changes

The title of the pull request will be included in the release notes.

2023-05-01 01:59 UTC, mkllnk requested changes

2023-05-01 01:59 UTC, mkllnk commented on config/application.rb
> -
Great. I'm assuming that you also want to delete lib/session_cookie_upgrader.rb. This is still in draft. I could move it back or maybe I quickly do it and ready it for review.

2023-05-01 03:45 UTC, mkllnk approved these changes

2023-05-05 05:24 UTC, dacook approved these changes
Good cleanup. Should we test that a staging deployment doesn't kill an active session just in case?

2023-05-08 02:50 UTC, mkllnk commented
>  Should we test that a staging deployment doesn't kill an active session just in case?

I just had a very quick check even though I was 99.9% sure as well and yes, my login persisted. Merging.

2023-05-08 02:50 UTC, merged