[White Label] Make logo url link more tolerant in terms of format
openfoodfoundation/openfoodnetwork pull request #10922
Opened 2023-06-01 15:44 UTC by jibees

#### What? Why?

- Closes #10903

Makes URLs used in `LINK FOR THE LOGO USED IN SHOPFRONT` under the white label section, absolutized. 

#### What should we test?

- As a shop manager, edit the `LINK FOR THE LOGO USED IN SHOPFRONT` value. 
- Check that entering an URL without `http` or `https`, create actually an URL with a `http://` added
- Check that entering an URL starting with `http`, doesn't change the value of the URL

Therefor we do have an absolute URL.

#### Release notes

Changelog Category: User facing changes

The title of the pull request will be included in the release notes.

#### Dependencies

#### Documentation updates

2023-06-01 23:41 UTC, mkllnk approved these changes
Great, solved.

2023-06-01 23:41 UTC, mkllnk commented on app/models/enterprise.rb
> +    "http://#{self[:white_label_logo_link]}"
Shouldn't we use https by default? :shrug: 

Or maybe we should validate the URL on the model earlier. :thinking:

2023-06-01 23:41 UTC, mkllnk commented on spec/system/admin/enterprises_spec.rb
> +            it_behaves_like "edit link with", "openfoodnetwork.org", "http://openfoodnetwork.org"
I would have tested this on the model because it's much faster.

2023-06-02 00:06 UTC, dacook requested changes
I agree that we should try and validate this earlier to ensure the user supplies the correct value, rather than manipulating the string later.

2023-06-02 08:07 UTC, jibees commented
> I agree that we should try and validate this earlier to ensure the user supplies the correct value, rather than manipulating the string later.

I previously did not choose this solution, in order to be backward compatible with previous values. But you're right, it's not that important. On the other hand, validation based on HTML component, still allows user to POST _bad_ data. But it's an edge case, I agree. 
Back `In Dev` to change that, thanks!

2023-06-02 09:11 UTC, jibees commented
It's not that straightforward since we're on AngularJS form, and we need to take into account that validation by native HTML component. Will try.

2023-06-05 00:09 UTC, mkllnk commented
Can we also add a validation to the Enterprise model?

I'm just wondering which logic browsers apply when you type in the address bar. When you type example.com then it adds the http:// automatically. It's safe to assume http or https. I don't think that we need to force users to add http://.

There's probably a regex for valid URLs. Otherwise we can validate on the Enterprise model like this:

```
uri = URI(s)
uri = URI("http://#{s}") if uri.scheme.nil?
if uri.is_a? URI::HTTP # includes https
  self.white_label_logo_link = uri.to_s
else
  errors.add(...) unless uri.is_a? URI::HTTP # includes https
end
```

We also have an indirect dependency to the [addressable gem](https://github.com/sporkmonger/addressable). We could make that explicit and use its heuristic parsing:

* https://www.rubydoc.info/gems/addressable/Addressable/URI#heuristic_parse-class_method

2023-06-06 02:27 UTC, dacook approved these changes
Thanks for updating, great specs!

2023-06-06 02:27 UTC, dacook commented on app/models/enterprise.rb
> +    return if white_label_logo.blank?
I was going to suggest this dependency isn't necessary, but then remembered the link input field is hidden when the checkbox is unchecked. 
So it's not fair on the user to validate something they can't fix. (Eg if we removed this check, then the validation rules change in the future, an old hidden value could cause an error that the user can't see).

So all good 👍

2023-06-06 02:27 UTC, dacook commented on app/models/enterprise.rb
> +    self.white_label_logo_link = "http://#{white_label_logo_link}" if uri.scheme.nil?
I would have expected `https` to be the default, but it doesn't really matter. If it matters, the user can update it!

2023-06-07 03:06 UTC, mkllnk approved these changes

2023-06-07 03:06 UTC, mkllnk commented on app/models/enterprise.rb
> +    uri = URI(white_label_logo_link)
Nice. We could call `strip` on the input in case someone copies whitespace but it's not necessary.

2023-06-07 03:13 UTC, mkllnk commented
I decided that adding `strip` is small enough to quickly add and still progress to testing.

2023-06-07 07:51 UTC, jibees commented
> I decided that adding `strip` is small enough to quickly add and still progress to testing.

I agree. Thanks for updating my PR!

2023-06-07 07:51 UTC, jibees commented on spec/models/enterprise_spec.rb
> +      end
Thanks @mkllnk !!

2023-06-07 09:00 UTC, filipefurtad0 commented
Hey @jibees ,


As a shop manager, editing the LINK FOR THE LOGO USED IN SHOPFRONT value:

- Checked that entering an URL without `http` or `https`, create actually an URL with a `http://` added

`github.com/` -> `https://github.com/` :heavy_check_mark: 

- Check that entering an URL starting with http, doesn't change the value of the URL

`https://github.com/` -> `https://github.com/` :heavy_check_mark: 


The PR also introduces a validation, right? So, I've tried a test case "between the cracks", an invalid URL:

`://github.com/ ` -> validation error :heavy_check_mark: 
but a missing translation, too:
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/02108635-d8e0-4595-b2f3-24894d8a9bc1)

This looks good to go, I'll open an issue for the missing translation.

2023-06-07 09:00 UTC, merged