🚧 Products V3: Display "None" is a product is not assigned to a tax category
openfoodfoundation/openfoodnetwork pull request #11293
Opened 2023-07-27 13:59 UTC by jibees

The `tax_category` method on product is defined like this:

https://github.com/openfoodfoundation/openfoodnetwork/blob/55fbab4c0d6e56d6dd707c893f58c52507e8cc53/app/models/spree/product.rb#L208-L214

Thats why we need to check if product has a tax category before displaying its name. Otherwise, returns 'None'

 - I could also have created a `tax_category_name` method on Product, but I found it confusing
 - I could also have changed the `tax_category` method on Product, but I was afraid about the needed refactoring after that

#### What? Why?

- Closes #11291 

#### What should we test?

- With feature activated, check that a product that is not assigned to a tax category displays "None" in the table
<img width="1047" alt="Capture d’écran 2023-07-27 à 15 58 49" src="https://github.com/openfoodfoundation/openfoodnetwork/assets/296452/fc98f72a-3dee-4ee6-b471-bbd09b66473d">
<img width="1359" alt="Capture d’écran 2023-07-27 à 15 58 24" src="https://github.com/openfoodfoundation/openfoodnetwork/assets/296452/685c42a2-5d34-4b9d-8744-d0a82ea07e45">

- 

#### Release notes

Changelog Category: User facing changes

2023-07-27 14:36 UTC, RachL commented
@jibees when "none" we need to display blank in the table see https://github.com/openfoodfoundation/openfoodnetwork/issues/11161
Sorry for the poor issue description

2023-07-27 22:50 UTC, mkllnk requested changes

2023-07-27 22:50 UTC, mkllnk commented on app/views/admin/products_v3/_table.html.haml
> +          .line-clamp-1= product.tax_category_id.present? && product.tax_category&.name  || "None" # TODO: convert to dropdown, else translate hardcoded string.
You don't need `present?` on an id. It's either present or nil. And applying Rachel's comment:
```suggestion
          .line-clamp-1= product.tax_category_id && product.tax_category&.name  || ""
```

2023-07-28 01:35 UTC, dacook commented
I'm a bit confused actually. @mariocarabotta can you confirm if JB's screenshot at the top is correct, or what you'd expect to see?

From my understanding, we'd like it to show the same as whatever the dropdown shows (because indeed it will soon be a dropdown). In this case, "None".

2023-07-28 05:53 UTC, mariocarabotta commented
I was thinking to actually show a text string saying _None_. As you said, it will eventually become a dropdown, which should show the selected value.
![Screenshot 2023-07-28 at 14 50 18](https://github.com/openfoodfoundation/openfoodnetwork/assets/6696729/5ebd58f2-b4ae-4ced-a05f-dd3fff31b21e)

This implementation seems correct to me
![Screenshot 2023-07-28 at 14 52 54](https://github.com/openfoodfoundation/openfoodnetwork/assets/6696729/b63f48dc-0f16-4bf9-828b-29e9c7d0df71)

2023-08-09 09:33 UTC, jibees commented
Closing in favor of https://github.com/openfoodfoundation/openfoodnetwork/pull/11156

2023-08-09 09:33 UTC, closed without merging