[Product Refactor] Remove multiple taxons
openfoodfoundation/openfoodnetwork pull request #11346
Opened 2023-08-07 15:00 UTC by Matt-Yorkley

#### What? Why?

Related to #9069 

Removes a bunch of unused code and functionality around Taxons. This is a hangover from Spree, where theoretically a product could have multiple taxons (product categories). We only have **one** taxon per product, there's no way to actually set more than one.

This is a bit of prep for migrating taxons from products to variants (but we're keeping only the `primary_taxon_id` and removing this weird mess around multiple taxons per product).

Review note: this unused "multiple taxons" functionality is handled via a class called `Spree::Classification` which represents a join table called `spree_products_taxons`. A product's taxon is still tracked by the `primary_taxon_id` attribute.

#### What should we test?

Not sure what can be manually tested, we're just removing some unused functionality here.

#### Release notes

Changelog Category: Technical changes

The title of the pull request will be included in the release notes.

2023-08-08 03:37 UTC, dacook requested changes
Great job, a nice tidy-up.

I see even more more code that can be deleted, so will go ahead.

2023-08-08 03:37 UTC, dacook commented on spec/components/product_component_spec.rb
> -    end
Actually this is the only example in the block, so the whole block can be deleted 🧹

2023-08-08 03:37 UTC, dacook commented on spec/serializers/api/enterprise_shopfront_serializer_spec.rb
> -    expect(serializer.serializable_hash[:taxons].to_json).to match 'Veg'
At first I was thinking "hey, there shouldn't be multiple taxons anymore."
But a shopfront has multiple products, so of course continues to have multiple taxons 👍

2023-08-08 03:37 UTC, dacook commented on spec/system/admin/reports_spec.rb
> -      product2.taxons = [taxon]
Hum, this spec works on the factory data for primary taxon. 
Shrug, not worth  updating.

2023-08-08 03:38 UTC, dacook approved these changes

2023-08-08 03:47 UTC, dacook requested changes
I got trigger-happy and missed the linter error:

```
app/models/spree/taxon.rb:8:5: C: Rails/HasManyOrHasOneDependent: Specify a `:dependent` option.
```

The Products class says it requires a primary_taxon to be present, but the Taxon class doesn't specify what to do when it is deleted.
The options are here:
https://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html#method-i-has_many-label-Options

We could explicitly specify the current behaviour:
`dependent: nil`

But I think it makes more sense to `:restrict_with_error` (causes an error to be added to the owner if there are any associated objects). What do you think?

2023-08-08 05:32 UTC, dacook commented
PS I found that I wasn't able to revert my dev environment so updated the migration to make it easy.

2023-08-08 06:34 UTC, rioug approved these changes
I am always happy to see less code :1st_place_medal:

2023-08-08 10:25 UTC, Matt-Yorkley commented
> I think it makes more sense to :restrict_with_error

Yeah nice catch, I think similar behaviour was provided before through the `Classification` class. I'll add it now :+1:

2023-08-08 23:38 UTC, dacook approved these changes
Cool 👍

2023-08-08 23:47 UTC, dacook commented
Regarding testing: I think it would be worth some manual testing around categories. There _shouldn't_ be any visible changes, but I'm not confident enough to be able to guarantee it. I think it's important enough to manually verify.
Not being very familiar with categories, I can only suggest the basics, ie:

1. Add/update category on a product
2. Try filtering products by category as a customer
3. Check that it appears in a report

I'll add the above to the description, but @Matt-Yorkley feel free to chime in if this is really unnecessary.

2023-08-09 09:18 UTC, drummer83 commented
Hi @Matt-Yorkley,
Thanks for working on this! I have tested on staging AU.

I can confirm the following:
- Changing taxons of a product as enterprise user works as before. :heavy_check_mark: 
- Creating, editing and deleting taxons as super admin user works as before. :heavy_check_mark: 
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/4be49524-60b9-444c-8a43-4c61bb8e50eb)
- Filtering in the shopfront and checking out works as before. :heavy_check_mark: 
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/3c490c7f-64da-467a-a174-545cd03b64e6)
- Taxons are showing up in the reports as before. :heavy_check_mark: 
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/873ed9d2-beca-4eba-a121-dc7aafbcb522)

All seems to be good. :partying_face: 
Merging! :rocket: 
Thanks!

2023-08-09 09:19 UTC, merged