Fully Enable Vouchers Feature Toggle by Default
openfoodfoundation/openfoodnetwork pull request #11831
Opened 2023-11-18 13:16 UTC by chahmedejaz

#### What? Why?

- Closes #11827

- Added a migration to fully enable the vouchers feature toggle by default

#### What should we test?

- After the deployment, go to the Flipper UI
- Please validate that the feature toggle for the `vouchers` has been fully enabled.

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [x] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [x] Feature toggled

2023-11-19 22:31 UTC, mkllnk requested changes

2023-11-19 22:31 UTC, mkllnk commented on db/migrate/20231118125941_activate_voucher_by_default.rb
> +  def change
The change method is also executed when rolling back a migration. But in that case we don't want the feature to be enabled again. Let's change it to `up`.
```suggestion
  def up
```

2023-11-19 22:32 UTC, mkllnk approved these changes

2023-11-19 23:45 UTC, rioug approved these changes
Thanks for your help !

2023-11-21 13:45 UTC, drummer83 commented
Hi @chahmedejaz,
Thanks for another pull request!

## Switching OFF to ON
I staged this PR on our AU server, where I had the feature toggle switched OFF before:
![grafik](https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/d2388f64-146d-456a-8c1b-eca1c6208a28)

After staging the toggle was switched ON and vouchers were available:
![grafik](https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/a5068abe-9afd-422b-a3da-cf78f9174fe9)

![grafik](https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/f480bbf2-05f1-4462-ae01-47638f421014)

## Switching ON to ON
I also staged this PR on our UK server, where I had the feature toggle switched ON before:
![grafik](https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/ef5fee5e-9804-48e2-8572-7f522971425a)

After staging the toggle was still switched ON and vouchers were available:
![grafik](https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/0eff0209-751b-4b08-bc7e-d00fd487b140)

![grafik](https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/f0d13c1f-cb63-4e45-8c03-019a0556ded5)

## Result
Seems to work well! :muscle: 
Thanks again! Merging! :tada:

2023-11-21 13:45 UTC, merged