Replace toggle_button_disable controller with generic toggle_control controller
openfoodfoundation/openfoodnetwork pull request #12050
Opened 2024-01-16 20:04 UTC by cyrillefr

- add `enableIfPresent method in `toggle_control_controller.js` to handle enabling on toggle
- add testing in the corresponding spec
- replace in view previous controller with intended generic toggle-control

#### What? Why?
See #11928 
Does not close the issue, as this is a replacement for the first of the three old/tailored/legacy controllers.

The replaced controller was used only to toggle disability of the button to add a voucher at the checkout.

I have forgot to remove the previous controller and its spec though ...

#### What should we test?
Make a checkout and see if button to add voucher is disabled at first and then enabled when data is entered.
Or this trick:
`rspec spec/system/consumer/checkout/payment_spec.rb:128`  with putting a `binding.pry` to stop the test and see the page where the checkout + voucher is made. Need to alter cuprite setting too (headless: false)

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [ ] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [x] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

#### Dependencies

#### Documentation updates

2024-01-17 15:21 UTC, cyrillefr commented
Hello @dacook, could it be possible to rerun tests as they failed at "Install JS dependencies" ?

2024-01-17 16:21 UTC, sigmundpetersen commented
done @cyrillefr

2024-01-18 00:10 UTC, dacook requested changes
Great, this looks perfect to me!

Just a couple of things, one below, and as you mentioned:
> remove the previous controller and its spec


Would you be able to add that as a new commit to this PR?

2024-01-18 13:26 UTC, cyrillefr commented on app/webpacker/controllers/toggle_control_controller.js
>    //todo: can a new method disableIfBlank replace ButtonDisabledController?
Done :)

2024-01-18 22:08 UTC, dacook approved these changes
Wonderful, thank you!

2024-01-18 22:11 UTC, mkllnk approved these changes

2024-01-22 16:26 UTC, cyrillefr commented
Hello @dacook ,

Could it be possible to merge this PR ?
I will have to make modifications to the same js controller file for the next PR that tackles #11928. (I am talking `app/webpacker/controllers/toggle_control_controller.js` that was modified).
I would rather avoid conflicts later :)

2024-01-22 22:02 UTC, dacook commented
Hi @cyrillefr , sorry for the delay. As this affects the front end, we need to verify with a manual test before merging, just in case any unforeseen issues come up. We have a few items in the testing list at the moment so it may have to wait a little while.

In a case like this, and if you're confident with Git, I would suggest that you can create a new branch from this one, to start your next task. There's a small risk of conflicts if this branch will get changed after testing, but it seems unlikely in this case.

2024-01-23 08:36 UTC, cyrillefr commented
Hello @dacook ,

Thank you for the clarification. My goal was certainly not to rush anyone :)

Did not know I could on github make a branch from another one.
I will go on the simpler way and wait for this one to be merged to put the next step.

2024-01-24 15:39 UTC, drummer83 commented
Thank you, @cyrillefr!

I can confirm that the apply button for the voucher code is still working correctly.

https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/6b01c2ed-321e-48ce-980e-3a0019843fd9

Great, I will merge this one and you can feel free to take the next step of this consolidation. :muscle: 

Thanks again! Merging! :partying_face:

2024-01-24 15:39 UTC, merged