Fix rubocop Lint/DuplicateMethods
openfoodfoundation/openfoodnetwork pull request #12350
Opened 2024-04-08 15:30 UTC by anansilva

#### What? Why?

- Part of Fix Rubocop Lint issues [#12330](https://github.com/openfoodfoundation/openfoodnetwork/issues/12330)

Fixed the `Lint/DuplicateMethods` offense. 

`sso_secret` is defined at both `attr_accessor` and `lib/discourse/single_sign_on.rb:66`

`sso_url` is defined at both  `attr_accessor`  and `lib/discourse/single_sign_on.rb:70`

#### What should we test?

Fix seems pretty safe since we are just removing duplicate instance methods. But might be worth testing SSO to discourse.

#### Release notes

Changelog Category: Technical changes

#### Dependencies

#### Documentation updates

2024-04-09 00:22 UTC, rioug approved these changes
Thanks @anansilva ! It looks good :+1:

2024-04-10 00:19 UTC, dacook requested changes
I think this might actually break things, which are not tested. 
But before we proceed any further, I'll try to find out if it's even used...

I've posted in [#delivery-circle](https://openfoodnetwork.slack.com/archives/C01T75H6G0Z/p1712708679583339), so let's pause until we can resolve that question.

2024-04-10 00:19 UTC, dacook commented on lib/discourse/single_sign_on.rb
>        raise "sso_secret not implemented on class, be sure to set it on instance"
Hmm I don't see the instance method declared elsewhere, so I wonder if it's confused the class method as a duplicate.

I can't actually find any specs covering this, so I tried constructing a quick test in the console:

```
require 'discourse/single_sign_on'
sso = Discourse::SingleSignOn.parse("query_string", "secret")
```
```
NoMethodError: undefined method `sso_secret=' for #<Discourse::SingleSignOn:0x0000000114c12798>

      sso.sso_secret = sso_secret if sso_secret
         ^^^^^^^^^^^^^
Did you mean?  sso_secret
```

This is obviously not an exhaustive test, so we should either add specs, or  definitely do a manual test of the functionality. Hmm, but I can't find any documentation about this.. I wonder if it's even used...

2024-04-10 00:19 UTC, dacook commented on lib/discourse/single_sign_on.rb
>        raise "sso_secret not implemented on class, be sure to set it on instance"
`±` To fix: the class methods (`self.sso_secret` etc) seem unnecessary, so I'd consider removing them instead. And why not move `:sso_secret, :sso_url` to the `ACCESSORS` list.. 

But still I'd like to confirm if it's worth it first.

2024-04-10 03:30 UTC, dacook requested changes

2024-04-10 03:30 UTC, dacook commented on lib/discourse/single_sign_on.rb
>        raise "sso_secret not implemented on class, be sure to set it on instance"
Update: this whole file is unused and so I've [scheduled for removal](https://github.com/openfoodfoundation/openfoodnetwork/issues/12355).

For now, I suggest we add `rubocop:disable` for this whole file and move on.

2024-06-03 10:56 UTC, sigmundpetersen commented
Hey @anansilva 👋 Do you want to continue this?
Note that Discourse SSO was removed in #12496

2024-08-27 10:52 UTC, sigmundpetersen commented
Closing. Please reopen if you want to continue this one Ana 👍

2024-08-27 10:52 UTC, closed without merging