[VCR/Stripe] Tests payment intents for offline payments
openfoodfoundation/openfoodnetwork pull request #12408
Opened 2024-04-22 16:32 UTC by filipefurtad0

#### What? Why?

- Contributes/closes #11890 

Subscriptions use payment intents with a set up customer, for offline payments, i.e., payments in which the customer is not online, at the moment of checkout.

Before we were only testing regular payment intents, with a guest customer.

This PR adds tests around payment intents which have a customer previously set up, for offline payments.

Please note, that **this PR does not test OFN code**. It serves as a proof of concept, that we can trigger the correct card responses in both scenarios (with and without a setup customer).

I have not found a Stripe spec directly addressing subscriptions or setting offline payments; I think it would need to be created from scratch.

#### What should we test?

- green build.

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [ ] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [x] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

#### Dependencies

#### Documentation updates

2024-04-23 00:03 UTC, dacook requested changes
The code looks good, just added one note but perhaps it's more of an opinion.  `±` The linter step failed though.

So this specifies some of the Stripe behaviour, (which I guess is also documented by Stripe). 
Do you intend to keep these, or is the next step to use them as a starting point for creating the OFN specs?

2024-04-23 10:36 UTC, filipefurtad0 commented
> The linter step failed though.

This is occurring when we introduce too many new lines, also when we re-record Stripe cassettes - [it started on version 10.14.0 I believe](https://github.com/openfoodfoundation/openfoodnetwork/pulls?q=is%3Apr+is%3Aclosed+bump+stripe+).

> Do you intend to keep these, or is the next step to use them as a starting point for creating the OFN specs?

I would say these are good to keep for now, while we don't have specific specs for subscriptions. These tests could potentially catch breaking changes around payments setup for future use, when bumping Stripe versions. But, yes, we can consider removing these, once we write more specific tests.

2024-04-23 11:27 UTC, filipefurtad0 commented on spec/lib/stripe/payment_intent_validator_spec.rb
> +            end
Thanks @dacook , I've moved the customer block and the let variables outside the shared_examples block.

2024-04-23 23:35 UTC, dacook commented
> This is occurring when we introduce too many new lines

That's funny, the diff is indeed large, but most of it is YAML, which Rubocop is configured to ignore.
This will probably solved by [Test all files with Rubocop, not just added code in the diff](https://github.com/openfoodfoundation/openfoodnetwork/pull/12393#top).

2024-04-24 00:14 UTC, mkllnk approved these changes

2024-04-24 00:14 UTC, merged