Bumps knapsack
openfoodfoundation/openfoodnetwork pull request #12442
Opened 2024-05-06 16:59 UTC by filipefurtad0

Comments out queue split setting for system specs

#### What? Why?

- Closes # 

#### What should we test?

- Visit ... page.
- 

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [ ] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

#### Dependencies

#### Documentation updates

2024-05-07 01:34 UTC, rioug commented on .github/workflows/build.yml
> +          # KNAPSACK_PRO_FIXED_QUEUE_SPLIT: true
What's the reason behind disabling queue mode ?

2024-05-07 05:14 UTC, mkllnk requested changes
Cool that you got it working. I'm not sure that we should go that way though. Is there an issue on the Knapsack repository?

2024-05-07 05:14 UTC, mkllnk commented on Gemfile
> +  gem 'knapsack_pro', '7.0.0'
We shouldn't restrict the version here. You might do that manually to update to a certain version but you don't need to commit this.

2024-05-07 05:14 UTC, mkllnk commented on .github/workflows/build.yml
> +          bundle exec rake knapsack_pro:rspec
I guess that the changes to queue mode don't work well with webpacker but do we know why?

Is it more important to upgrade Knapsack or to have queue mode? We could decide not to upgrade until Knapsack fixed this... or we removed webpacker.

2024-05-07 05:14 UTC, mkllnk commented on Gemfile
> +  gem 'knapsack_pro', '7.1.0'
This will prevent Dependabot from suggesting any more updates. We shouldn't define a version here unless it's necessary.

2024-05-07 15:53 UTC, filipefurtad0 commented
I'd prefer to enable queue mode and get it all to work on this PR, but I don't think I'm there yet. The latest change (explicitly enabling webpacker on each system spec node) fixed the webpacker issue but now we're having:
```

      NoMethodError:
        undefined method `keys' for nil:NilClass
      
              b.slice(*(b.keys - a.keys))
```

pretty much everywhere, like here:

```

  10) full-page cart viewing the cart updating quantities with insufficient stock available shows the quantities saved, not those submitted
      Failure/Error: example.run
      
      NoMethodError:
        undefined method `keys' for nil:NilClass
      
              b.slice(*(b.keys - a.keys))
                         ^^^^^
      # ./spec/system/support/cuprite_setup.rb:39:in `block (2 levels) in <top (required)>'
      # ./spec/base_spec_helper.rb:101:in `block (3 levels) in <main>'
      # ./spec/base_spec_helper.rb:101:in `block (2 levels) in <main>'
```

I'm not sure what to make of this yet...

2024-05-08 10:04 UTC, filipefurtad0 commented
Closing in favor of #12447 :muscle:

2024-05-08 10:04 UTC, closed without merging