notify the user if any order cannot be invoiced on bulk invoice sending
openfoodfoundation/openfoodnetwork pull request #12458
Opened 2024-05-09 14:28 UTC by abdellani

#### What? Why?

- Closes #12374 

#### What should we test?

- Visit ... page.
- 

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [ ] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

#### Dependencies

#### Documentation updates

2024-05-20 00:31 UTC, rioug requested changes

2024-05-20 00:31 UTC, rioug commented on app/reflexes/admin/orders_reflex.rb
> +        abn: [nil,""],
The empty string `abn`isn't cover by specs, could you update that ?

2024-06-11 00:14 UTC, rioug approved these changes
All Good now, Thanks @abdellani !

2024-06-11 05:36 UTC, mkllnk approved these changes

2024-06-12 22:48 UTC, filipefurtad0 commented
Hey @abdellani ,

Tried both described scenarios, after making ABN mandatory for the instance, and deleting the ABN for the enterprise. On the orders page:

- attempting to print the invoice

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/abe6a0b2-6e8d-4395-8d40-a7ab972599a1)


- attempting to send the invoice per email

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/9deccb41-c730-4c53-a438-4f645568bad4) 

Looks great! Merging :-)

2024-06-12 22:48 UTC, merged