log who deleted products
openfoodfoundation/openfoodnetwork pull request #12457
Opened 2024-05-09 13:41 UTC by abdellani

#### What? Why?

- Closes #12452 

#### What should we test?

- Visit ... page.
- 

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [ ] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [x] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

#### Dependencies

#### Documentation updates

2024-05-14 01:38 UTC, dacook requested changes
Hi Mohammed, great to see you! Thanks, yes I think this is good 👍 

In my [other PR](https://github.com/openfoodfoundation/openfoodnetwork/pull/12431/commits/a38f22fbee56f0e287c090deb0625281086f3f6b) I tried overwriting the `destroy` method so that you can pass the user_id as a parameter. It's a little cleaner and seems to be fine, but your approach of using standard rails callbacks is probably safer in the long run.

Just a little rubocop issue to fix.

2024-05-20 00:15 UTC, rioug commented
@dacook the issue mention using a separate log file to record product deletion, the solution uses the usual log file are you happy with that ?

2024-05-20 00:22 UTC, dacook approved these changes
Yep, that's ok with me.
* Of course, it means more messages in the one file to sift through when you're debugging. But it could also be beneficial, giving you a bigger picture.
* Also, more messages could mean logs are rotated quicker. But I propose we focus on that [separately](https://github.com/openfoodfoundation/ofn-install/issues/927).

2024-05-20 00:25 UTC, dacook commented
PS this PR uses log level `:info`, which makes perfect sense. 
I just checked and both staging and production environments are currently configured to `:info`, so this will ensure it is logged 👍

2024-05-20 00:36 UTC, dacook commented
Tested in dev environment:

```
10:29:43 rails.1   | Spree::Product 13 deleted by 1
```

I noticed a couple of things:
1. So far this only logs when the user_id is provided. We could enhance it to always log even when the user_id is unknown (eg just "`Spree::Product 13 deleted`"`). Then it would be super easy to add the module to many models, and would cover all methods of deleting (it doesn't currently cover deleting from the new products_v3 screen).

2. The user_id isn't named, so it's not clear what the number is. It might be helpful to also log the user's name or email. Eg: "`Spree::Product 13 deleted by user 1 <example@email.com>`"

Maybe something to consider in the next round.

2024-05-20 00:37 UTC, merged

2024-05-20 00:40 UTC, dacook commented
Oops, I just realised @rioug  didn't approve yet! Oh well, please comment on the associated issue if you have suggestions for the next step :)

2024-05-20 01:51 UTC, rioug commented
All good, I am happy with the code