Update and Recalculate Fees after Order Adjusted in Backend
openfoodfoundation/openfoodnetwork pull request #12538
Opened 2024-05-31 14:41 UTC by cyrillefr

#### What? Why?

- Closes #12512 

#### What should we test?
- log as an admin or hub's owner (classical/legacy mode)
- visit `admin/orders`
- pick an order from the list, one that is complete, but with a transaction fee associated to a payment method
    like a card payment
- one should see a non zero transaction fee under `ORDER ADJUSTMENTS`
- add a product from the `Select a variant` select box
- chose a quantity from the newly showed line
- click on the `+` sign to add the product/variant to the order
- the transaction fee should be updated

#### Extras
The `UPDATE AND RECALCULATE FEES` is for shipment fees only.
A click on it executes this line:
`@order.shipments.map(&:refresh_rates)` from the `edit` method in the `orders` controller.

But the recalculation is in the `ensure_correct_adjustment` method in the `payment` model.
That is triggered by an `after_save` hook.
That is triggered when (amongst others I guess) a new product is added in the dashboard.
Problem was, no recalculation of the amount was made in the update mode, only in the create mode.

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [X] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [X] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

#### Dependencies

#### Documentation updates

2024-06-03 04:26 UTC, rioug commented on spec/system/admin/order_spec.rb
> +
You should be able to remove the `sleep` by checking the variant is added on the page.

2024-06-03 04:31 UTC, rioug requested changes
Nice one, thanks @cyrillefr :pray: 
Could you try to remove the `sleep` the spec ? It's considered bad practice to have use `sleep`, they can be source of flackyness amongst other things.

2024-06-04 02:28 UTC, rioug approved these changes

2024-06-04 23:12 UTC, mkllnk reviewed
> The UPDATE AND RECALCULATE FEES is for shipment fees only.

Where does this spec come from?

I would have expected the fee to be updated when the recalculate-button is clicked, not when the product is added. The transaction fee is supposed to cover the cost of Stripe. If the customer paid already then the current fee is reflecting the cost incurred because of the finished transaction. The admin may add a product for free or the difference is paid in cash at delivery. That's my understanding but the instance managers would know better.

2024-06-09 13:06 UTC, cyrillefr commented
Hello @mkllnk ,

This is what I understand from reading the source.
Clicking on `UPDATE AND RECALCULATE FEES` leads to the `edit` method in `orders_controller.rb`.

That is:
```ruby
def edit                                       
  @order.shipments.map(&:refresh_rates)
end
```
The `refresh_rates` method deals only with refreshing shipment rates.
Then, on save, are triggered these 2 methods:
```ruby
after_save :ensure_correct_adjustment, :update_adjustments
```
```ruby
def ensure_correct_adjustment
  if fee_adjustment
    fee_adjustment.originator = shipping_method
```
With `fee_adjustment`:
```ruby
def fee_adjustment
  @fee_adjustment ||= adjustments.shipping.first 
end
```
And `update_adjustments` leads to
```ruby
Spree::ItemAdjustments.new(self).update
```
So, there is no update regarding payment transaction.
Also, the button to recalculate is on the Shipment subpage.

2024-06-11 00:39 UTC, mkllnk commented
> the button to recalculate is on the Shipment subpage.

I was talking about the button on the order edit page:

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/3524483/61da05e8-1f84-4637-82ea-01cc65b49ba8)

2024-06-11 06:47 UTC, cyrillefr commented
Hello @mkllnk ,

Aargh I am sorry, I mis typed :), I am talking about the same button, the thing I wanted to highlight is: it is not in the `payments` subpage.

2024-06-11 12:16 UTC, cyrillefr commented
Accidentally deleted my project branch. Restored and reopened.

2024-06-11 22:32 UTC, mkllnk commented
@RachL, could you give some input here? Shall we add a recalculate button on the payments page?

2024-06-12 09:45 UTC, RachL commented
@mkllnk I don't think it is a good idea to add a button in the payment page. Users won't see it and will forget to click on it. If this means we need to update the fees when we add the product and not when users are clicking on the update button of the edit page, then let's do it.

2024-06-12 23:20 UTC, mkllnk commented
Okay, let's go ahead with this then.

2024-06-12 23:21 UTC, mkllnk approved these changes

2024-06-13 00:59 UTC, filipefurtad0 commented
Hey @cyrillefr ,

Thanks again for this contribution.

I've verified the issue: indeed, the value of a flat percent transaction fee was not updated, neither when a line item was added/removed, not when clicking the Update and Recalculate fees button.

After this PR, orders which were previously edited and still had an incorrect transaction fee, can now be corrected by clicking Update and Recalculate button:

Before clicking the button:

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/5e357f8a-6fef-4c3d-91cc-9d8e13d1b19d)

After clicking the button - we can see the fee was updated:

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/7c3de4c8-eff8-4244-9af0-f57704e328ae)

Also, adding a line item to the order automatically updates the value:

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/d725a041-7214-454d-aaec-8fed1d5b47ae)

This looks great! Thank you, merging.

2024-06-13 14:53 UTC, merged