Solve Rubocop RedundantInterpolation cops
openfoodfoundation/openfoodnetwork pull request #12575
Opened 2024-06-17 13:35 UTC by zanetagebka

#### What? Why?

- Part of [#6055](https://github.com/openfoodfoundation/openfoodnetwork/issues/6055)

#### What should we test?
Rather safe one. Just removed two cops

Cop: [RedundantInterpolation](https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/RedundantInterpolation)

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [ ] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

#### Dependencies

#### Documentation updates

2024-06-18 03:52 UTC, mkllnk requested changes
Great, the change is good but somehow a temporary file path was added. Can you remove that?

Thank you!

2024-06-18 03:52 UTC, mkllnk commented on .rubocop_todo.yml
> +    - 'tmp/stimulus_reflex_installer/working/development.rb'
This folder should not be tracked.

2024-06-18 03:52 UTC, mkllnk commented on .rubocop_todo.yml
> +    - 'tmp/stimulus_reflex_installer/working/development.rb'
This shouldn't be here.

2024-06-18 10:51 UTC, zanetagebka commented on .rubocop_todo.yml
> +    - 'tmp/stimulus_reflex_installer/working/development.rb'
Sure, I will push change today later.

2024-06-18 22:58 UTC, rioug approved these changes
Looks good now , thanks @zanetagebka :pray: 
Note for next time, we prefer rebasing the branch on master instead of merging it, it keeps the git history cleaner.

2024-06-19 01:01 UTC, mkllnk approved these changes
Perfect!

2024-06-19 01:01 UTC, merged