[BUU] Refactors products_v3 system specs
openfoodfoundation/openfoodnetwork pull request #12595
Opened 2024-06-20 15:37 UTC by filipefurtad0

The idea is to split the main spec into several smaller ones; these would share the helper file

#### What? Why?

- Contributes to #12497 

This PR starts refactoring and splitting v3 products spec. As proposed on issue #12497, it:

- Extracts helper methods to a helper file
- Moves the `sorting, pagination and search` describe blocks to `products_v3/index_specs.rb`
- Moves the `updating, edit image` to `products_v3/update_specs.rb`

#### What should we test?

- green (and faster build?)

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [ ] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [x] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

#### Dependencies

#### Documentation updates

2024-06-20 15:46 UTC, sigmundpetersen commented
Hey @filipefurtad0 👋 I see also @chahmedejaz assigned himself on #12497 
You guys can coordinate on who does what 🙂

2024-06-20 15:55 UTC, filipefurtad0 commented
I'll describe what I've done here and then ask you for your review @chahmedejaz, so you can go from there - does this sound good?

2024-06-20 16:19 UTC, chahmedejaz commented
> I'll describe what I've done here and then ask you for your review @chahmedejaz, so you can go from there - does this sound good?

Sure, @filipefurtad0 . Sounds good 🙂

2024-06-20 16:20 UTC, chahmedejaz commented
> Hey @filipefurtad0 👋 I see also @chahmedejaz assigned himself on #12497 
> You guys can coordinate on who does what 🙂 

Oh, I didn't know @filipefurtad0 was working on it.😅 I thought it was unassigned. 😅

2024-06-20 23:01 UTC, mkllnk approved these changes
Good improvement.

Looking at the helpers in more details I found a few things to improve but that can happen in a separate PR.

2024-06-21 07:45 UTC, chahmedejaz approved these changes
Great work!
The specs look way clean now. 🎉

2024-06-21 07:45 UTC, chahmedejaz commented on spec/support/products_helper.rb
> +  end
Yes, I think it's better if the `producer` is passed in the method arguments. Helper methods should not access variables other than their args.

2024-06-21 07:45 UTC, chahmedejaz commented on spec/support/products_helper.rb
> +    expect(page).to have_selector ".pagination .page.current", text: page_number.to_s
That's a great catch. It can be improved to be a more generic helper. 👍🏻

2024-06-24 03:57 UTC, dacook requested changes
Great, thanks for doing this. 
I think most comments are ok and are existing things that would be nice to fix.

`±` But it looks like we accidentally lost the 'listing' tests. I think at least one of them is worth keeping.

2024-06-24 03:57 UTC, dacook commented on spec/support/products_helper.rb
> +  end
These are all pretty generic helpers actually, and maybe could be better shared.

2024-06-24 03:57 UTC, dacook commented on spec/system/admin/products_v3/products_spec.rb
> -  end
`±` This `describe "listing"` block was removed. Maybe the first test isn't really necessary, but the stock test looks valuable.

2024-06-24 03:57 UTC, dacook commented on spec/system/admin/products_v3/update_spec.rb
> +RSpec.describe 'As an enterprise user, I can manage my products', feature: :admin_style_v3 do
It's trivial, but seems like a good idea to give this a more specific name:

```suggestion
RSpec.describe 'As an enterprise user, I can update my products', feature: :admin_style_v3 do
```

2024-06-24 03:57 UTC, dacook commented on spec/system/admin/products_v3/products_spec.rb
> -        expect(page).to have_selector row_containing_name(p2.name.to_s)
Hmm maybe we should expand this spec to check the values of all fields.

2024-06-24 04:58 UTC, dacook commented on spec/support/products_helper.rb
> +  end
But let's avoid changing them right now because it will make https://github.com/openfoodfoundation/openfoodnetwork/pull/12562 harder to rebase.

2024-06-24 04:59 UTC, dacook commented
Just noticed that this will conflict with the [Product Refactor PR](https://github.com/openfoodfoundation/openfoodnetwork/pull/12562/commits/27c447cb8b48b3b00b5a99a1e60d670449dfbf7d), eek. 

I don't think it's worth holding this PR back, because that PR will take a while to get merged. And this PR will block/conflict with other BUU changes. But happy to hear if any other thoughts.

2024-06-24 08:05 UTC, RachL commented
Yes I agree @dacook we can't postpone BUU because of product refactor now :/

2024-07-02 06:57 UTC, dacook commented on spec/system/admin/products_v3/products_spec.rb
> -  end
Ok now I see that this was duplicated, so it's simple cleanup.

2024-07-02 06:59 UTC, dacook approved these changes
Rebased and fixed conflicts.

I now see that it wasn't removing an important spec, so all ready to go 👍

2024-07-02 06:59 UTC, merged