Fixes Rails/RelativeDateConstant offense
openfoodfoundation/openfoodnetwork pull request #12601
Opened 2024-06-21 21:15 UTC by cyrillefr

#### What? Why?

Contributes to #11482 

The: [Rails/RelativeDateConstant Cop](https://docs.rubocop.org/rubocop-rails/cops_rails.html#railsrelativedateconstant) checks whether constant value isn’t relative date. Because the relative date will be evaluated only once.

Constant is relative date : Constant.since or Constant.ago.

However here, expiration date should stay the same for the same instance hence, in init.
Spec has been modified accordingly

#### What should we test?
Nothing.
Automatic specs should all pass.

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [ ] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [X] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

#### Dependencies

#### Documentation updates

2024-06-21 21:36 UTC, chahmedejaz approved these changes
Nicely done 🎉

Just a small suggestion in the `RemoveTransientData`. :)

2024-06-21 21:36 UTC, chahmedejaz commented on lib/tasks/data/remove_transient_data.rb
> +    Spree::StateChange.where("created_at < ?", @expiration_date).delete_all
It would be great if we could use the attr_reader for `@expiration_date` in this class as well i.e. `expiration_date`.

2024-06-24 05:01 UTC, rioug requested changes
Good one, thanks @cyrillefr :pray: , could you just address @chahmedejaz comment ?

2024-06-24 08:48 UTC, chahmedejaz approved these changes
Perfect, Thanks, @cyrillefr  🎉

2024-06-24 23:15 UTC, rioug approved these changes

2024-06-24 23:15 UTC, merged