Use public contact email at the bottom of order confirmation email [OFN-12509]
openfoodfoundation/openfoodnetwork pull request #12654
Opened 2024-07-09 19:03 UTC by wandji20

#### What? Why?

- Closes #12509

Replace enterprise owner email with enterprise email in customer order confirmation email sign off.

#### What should we test?
Add items to the cart and create an order.
Now check that the conformation email is the same as the email set as public email in enterprise contact settings

- Visit ... page.
http://localhost:3000/fredo-s-farm-hub/shop#/shop_panel

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [ ] User facing changes

Use enterprise public contact email at the bottom of order confirmation email 

The title of the pull request will be included in the release notes.

#### Dependencies
N/A

#### Documentation updates
N/A

2024-07-19 08:16 UTC, RachL commented
@wandji20 by the way you have a couple of PR which have been started like this one. In case you don't want to work on it let us know, we can leave the issue open for other to take :)

2024-07-19 09:30 UTC, wandji20 commented
Hi @RachL This one is ready for review

2024-07-19 11:47 UTC, RachL commented
@wandji20 Awwesome! However it looks like this PR needs a rebase, can you have a look?

2024-07-22 01:24 UTC, rioug requested changes

2024-07-22 23:42 UTC, rioug approved these changes
Awesome, thank you !

2024-07-23 06:11 UTC, dacook approved these changes
It wasn't mentioned in the issue about falling back to the other email address, but I think it makes sense. Will add a note for testers to confirm.

I think Rails' `mail_to` helper would have made this simpler, but this solves it, thanks.

2024-07-23 08:04 UTC, wandji20 commented
@dacook 
I moved the logic for setting reply email to `app/helpers/mailer_helper.rb`

2024-07-23 23:21 UTC, rioug approved these changes
Nice one :+1: Quick note for next time, it's better to keep the git history once your PR has  been reviewed. Thanks !

2024-07-24 23:15 UTC, dacook approved these changes

2024-07-25 19:12 UTC, filipefurtad0 commented
Hey @wandji20 - it this your first PR? Welcome :tada: 

Before this PR:

![image](https://github.com/user-attachments/assets/b39a367f-a3c8-45c6-bcc5-1b06d82aaec3)

After this PR, and:

- changing the public address:

![image](https://github.com/user-attachments/assets/8abe7bc0-4a95-4fb7-81d5-1827091e4c9f)

We can see the public email address is displayed on the sent email :green_circle: 

- removing the public email address:

![image](https://github.com/user-attachments/assets/357aec71-8592-4ac8-bbfc-f7efe93c557a)

We can see that the enterprise email address is displayed :green_circle: 

It's looking good, merging!

2024-07-25 19:14 UTC, merged