Fix 'Back to products list' stateful navigation
openfoodfoundation/openfoodnetwork pull request #12735
Opened 2024-08-05 08:53 UTC by chahmedejaz

#### What? Why?

- Closes #12698 

#### What should we test?

- Visit ... page.
- 

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [ ] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

#### Dependencies

#### Documentation updates

2024-08-13 00:12 UTC, dacook requested changes
Great, a nice simple solution. 
Because it's using a session variable, I tried to imagine a case where it would remember the filters for too long and cause unexpected behaviour. But I couldn't think of any :)

I had a look at the previous solution, and saw that it used the `@url_filters` class variable. It seems that it was being passed around in order to remember the filters when moving across multiple pages (eg update product images, variants, properties etc). 

So you could have continued with that method. But this method is much simpler and less likely to break  (we don't have to remember to embed `@url_filters` everywhere, and inevitably there will be a break in the chain sometimes..). So I think it's a good move.

However the old `@url_filters` variable is still there on many pages, and has no effect because you've removed it from the button link.
Either we should remove it entirely, or at least continue to support it until we fully remove the old products screen. I think it would be as simple as adding it to the second part of `products_return_to_url` helper.

2024-08-13 09:31 UTC, chahmedejaz commented
Thank you so much @dacook and Sorry I didn't realize it's the same UI for old as well with different styling. 
Now just to be on the safe side, I've fixed it in such a way that the old UI will work just like before and our fix will only work in the new UI. Below is the respective change. Thanks
- https://github.com/openfoodfoundation/openfoodnetwork/pull/12735/commits/b14cd08990ea026bf42f3969397c732dc12faca1

2024-08-13 23:17 UTC, dacook approved these changes
Thanks Ahmed 👍

2024-08-15 00:20 UTC, mkllnk approved these changes
Nice simple solution.

It doesn't account for navigating in multiple tabs though. That's why the old solution was handing the filters around. That way we could pass on different filters in different tabs.

I'll approve this because it's better than before but I'm pretty sure that someone will raise a bug report about this.

2024-08-15 08:43 UTC, drummer83 commented
Hi @chahmedejaz,
Thank you for this fix. It's working well!

Filtering is preserved by
- name,
- product category,
- producer,
- on both user interfaces (v3 and legacy).

The new interface is also preserving the selection of 'x per page', which is great. The legacy design doesn't, but we can live with it.

The columns selection is not preserved, but this can be overcome by saving the selection as the default, so I think we're good here as well.

I was surprised to see the 'Back to products list' button only on the 'Product details' page. All other sub pages for editing products and variants don't show it. This could be improved but is out of scope here. So from those pages you either have to go to the Product details page first to find the button or you would click on 'Products' in the main navigation. In the latter case, the filter settings are lost - which is ok, I think, because it's like reloading the page.

So, all in all, I think we're good here. Merging! :rocket: 
Thanks again! :partying_face:

2024-08-15 08:43 UTC, merged