(Fix) chore(deps): bump wicked_pdf from 2.6.3 to 2.8.0 [OFN-12214]
openfoodfoundation/openfoodnetwork pull request #12743
Opened 2024-08-06 10:30 UTC by wandji20

#### What? Why?

- Closes #12214

Remove webpack compiled CSS from order pdf files

#### What should we test?
Generated order pdf from (print order) should work and look the same as before

- Visit ... page.
http://localhost:3000/admin/orders/

#### Release notes

(Fix) chore(deps): bump wicked_pdf from 2.6.3 to 2.8.0 [OFN-12214]

(Fix) chore(deps): bump wicked_pdf from 2.6.3 to 2.8.0

#### Dependencies
wicked-pdf

#### Documentation updates
N/A

2024-08-06 23:58 UTC, rioug requested changes
Removing the stylesheet from the pdf results in order looking differently (before on the right):
![print_order](https://github.com/user-attachments/assets/c221b855-3980-4f96-9f9f-3f81bf63847b)

2024-08-07 00:12 UTC, wandji20 commented
Thanks @rioug for reviewing
Did you test this in production or locally?

2024-08-07 00:22 UTC, rioug commented
> Did you test this in production or locally?

locally

2024-08-07 10:20 UTC, wandji20 commented
This should happen locally since `wicked_pdf` handles assets differently in development and production mode.
Working on this one, I did the following to ensure the gem will try and read assets like in production
- Unpack the gem with `gem unpack wicked_pdf` and adjust the code to mimic a production environment
- Precompiled assets

Then I noticed the `mail.scss` was not found in `wicked_pdf` asset finder method.
If we choose to move the mail-related styles to `app/assets/stylesheets` and precompile the new `mail.scss`
Then the asset will be found by `wicked_pdf` asset finder .

Can you please checkout this [conversation](https://github.com/openfoodfoundation/openfoodnetwork/pull/12214#issuecomment-2263425890) I had with Maikel

2024-08-12 01:33 UTC, rioug commented
> Can you please checkout this [conversation](https://github.com/openfoodfoundation/openfoodnetwork/pull/12214#issuecomment-2263425890) I had with Maikel

I had missed that sorry! 
I just tested the PR on staging and I get the same result :
![Screenshot Capture - 2024-08-12 - 11-29-25](https://github.com/user-attachments/assets/6d2b7993-b7e8-4c77-ab5f-d73d4c020898)

> If we choose to move the mail-related styles to app/assets/stylesheets and precompile the new mail.scss
> Then the asset will be found by wicked_pdf asset finder .

It looks like we'll need to do this, do you want to have a go at it ?

2024-08-12 23:28 UTC, rioug commented on config/application.rb
> +    config.assets.precompile += %w(mail.scss)
For consistency, could you use the syntax to create an array as the rest  of the file ?

2024-08-12 23:28 UTC, rioug commented
@wandji20 There is a a failing spec, could you have a look at it ?

2024-08-13 18:26 UTC, wandji20 commented on spec/system/admin/invoice_print_spec.rb
I am not so positive this is a good change.
So, I noticed a strange output in extracted text from pdf.
This is caused due to multi-line table header values.
Sadly, I could not figure out why it works when the `mail.scss` is compiled with Webpacker (before changes).

For an invoice with a header (see screenshot)
![image](https://github.com/user-attachments/assets/b3bea1aa-c0e0-4ebe-a6cc-4b2b9c193972)
I get this 
![Screenshot from 2024-08-13 19-08-20](https://github.com/user-attachments/assets/da15c705-eacc-4daf-bcc2-30201024a22a)
Seems to me it reads the header as two lines instead of one due to the longer header values spaning two lines

2024-08-15 00:30 UTC, mkllnk approved these changes

2024-08-15 00:30 UTC, mkllnk commented on spec/system/admin/invoice_print_spec.rb
This can happen in the conversion to text. It's very unfortunate but I don't think it can be easily solved. So we have to work with it for now.

2024-08-18 23:29 UTC, rioug approved these changes
Looks good :+1:

2024-08-19 13:38 UTC, RachL commented
@drummer83 BUU is about to be displayed to 75% of the users. And also dev and testers environment are displayed by default on admin style v3.
I think we can stop testing legacy version from now on :+1:

For invoice feature, I don't know when we will have budget to move forward, so you can also only focus on invoice with toggle OFF.

2024-08-22 15:34 UTC, drummer83 commented
Hi @wandji20,
Thanks for working on this one!

Here are my testing notes:

| Page | Invoice Template | Action | Result |
| - | - | - | - |
| Order list (bulk) | Standard | Print invoice | :heavy_check_mark: |
| Order list (bulk) | Standard | Send invoice | :heavy_check_mark: |
| Edit order | Standard | Print invoice | :heavy_check_mark: |
| Edit order | Standard | Send invoice | :heavy_check_mark: |
| Order list (bulk) | Alternative | Print invoice |  :heavy_check_mark: |
| Order list (bulk) | Alternative | Send invoice | :heavy_check_mark: |
| Edit order | Alternative | Print invoice | :heavy_check_mark: |
| Edit order | Alternative | Send invoice | :heavy_check_mark: |

The invoices are sent and printed correctly, the corresponding layout is applied. :heavy_check_mark: 

I came across some other issues while testing, but those are not related to this PR.
#12802 
#12803 

This one is ready to go! Great work! :tada: 
Thanks again! Merging! :rocket:

2024-08-22 15:34 UTC, merged