Task/12878 add variant name in od report
openfoodfoundation/openfoodnetwork pull request #12930
Opened 2024-10-17 06:56 UTC by chahmedejaz

#### What? Why?

- Closes # 

#### What should we test?

- Visit ... page.
- 

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [ ] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

#### Dependencies

#### Documentation updates

2024-10-17 09:52 UTC, dacook requested changes
Great work, and good thinking to migrate the options data to make it seamless for users.

I have a concern about the migration, do you think it's worth adding a test? Or are you confident you've already manually checked all possibilities?

2024-10-17 09:52 UTC, dacook commented on db/migrate/20241011071014_update_item_name_to_product_in_od_report.rb
> +        option.update(options: option.options)
I guess this works if `fields_to_show` is a pointer to the value inside the options hash. 
If that's the case, I think you should be able to simply call:
```suggestion
        option.save
```

But either way, I'm not sure as it's an uncommon way to do things, so I would like to see a test to check that it works.

2024-10-18 07:40 UTC, chahmedejaz commented
> I have a concern about the migration, do you think it's worth adding a test? Or are you confident you've already manually checked all possibilities?

@dacook - I'd manually tested all the possible use cases for this migration, I thought it would run only once so wasn't sure if it was worth a spec that would add up to the pipeline each time the workflow runs.
However, yes, I may have missed something in my manual testing, so I've added the specs for the use cases I could think of. Please review and let me know what you think about it. Thanks.

2024-10-20 23:29 UTC, dacook approved these changes
Wonderful, thank you.

Yes it's hard to know exactly what to spec or not. It's still production code that will modify data on every server, so I thought it worth being certain about exactly what it will and won't do.

I agree we don't need the test running every time, and maybe it would be possible to configure a runner to only test migrations when they are added. But I don't know if there's an easy way to do that. For now, I think we just occasionally archive the migrations and specs.

2024-10-20 23:47 UTC, rioug approved these changes
Looks good :+1:

2024-11-13 23:00 UTC, filipefurtad0 commented
Hey @chahmedejaz ,

Unfortunately, staging failed on both staging servers:

- staging-AU
https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/11827139747/job/32954654935

and

- staging-FR
https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/11827025386/job/32954294829

Moving back to In Progress for now.

2024-11-14 06:10 UTC, chahmedejaz commented
Thanks for raising this Filipe. I hope it will get fixed now.

@dacook - Here's the fix:
https://github.com/openfoodfoundation/openfoodnetwork/pull/12930/commits/39fa8e0acecb9f7a955b45735bd904988927d8dd

The migration class name was a bit different than the file name...Seems like I forgot to run the migration again after changing the name or something. 😞

2024-11-14 06:13 UTC, dacook approved these changes
Cool, looks like there has been a newer migration since this one was created, but that should be ok.

2024-11-14 06:23 UTC, chahmedejaz commented
Thanks @dacook for the quick response, are we good to move it to testing or do we need a second review? Thanks.

2024-11-18 02:31 UTC, filipefurtad0 commented
Hey @dacook and @chahmedejaz ,

I've tried several options to stage this PR, but even after resetting the DB with the suggested command (`~/apps/openfoodnetwork/current/script/ci/restore-staging-baseline.sh`) it keeps failing:

https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/11884093947/job/33111772141

Any ideas?

Thanks again.

2024-11-18 05:27 UTC, dacook requested changes
Ah, sorry I missed that there's a problem with the migration. This should have been picked up  during dev or CI testing, I'm not sure why it was missed.

Ahmed can you please look into this? The Good Migrations gem is linting our migrations to ensure they don't refer to application code. Migrations need to be completely independent, to ensure they always behave the same, no matter when they are executed.

In this case, I think you can simply define a basic ActiveModel class for table ReportRenderingOptions. See previous migrations for an example.

2024-11-18 06:19 UTC, chahmedejaz commented
Sure @dacook, it's done and pushed. Please review. I remember validating this migration before pushing to validate the case that the migration class is picked up successfully now, that's strange it didn't give this error then 😅 
Strangely, it didn't raise any error during the CI build as well.
Anyhow, hope it works now. Thanks

2024-11-18 06:21 UTC, dacook approved these changes
Thanks

2024-11-18 06:24 UTC, dacook commented
FYI @filipefurtad0 I've started deployment to AU staging.
There's one CI failure so far but I think it's a flaky one and can be ignored.

2024-11-18 06:36 UTC, chahmedejaz commented
CI specs got broken for this migration.
This is weird. This spec was working just before this change. Let me take a quick look

2024-11-18 06:38 UTC, chahmedejaz commented
The spec fails with the Basic ActiveRecord table. Strange again... Looking

2024-11-18 06:53 UTC, chahmedejaz commented
@dacook @filipefurtad0 - It's all green now. Sorry for the back and forth.

2024-11-18 22:14 UTC, dacook approved these changes

2024-11-20 18:23 UTC, filipefurtad0 commented
Hey again @chahmedejaz @dacook ,

I've placed an order with different variants and checked the report, before this PR:
![image](https://github.com/user-attachments/assets/84984b4b-280f-421c-b710-9d14063603fb)

and after this PR:
![image](https://github.com/user-attachments/assets/d659c96e-b001-437e-b3b9-9a792dcad43b)

It now displays the variant names, so I believe it makes the report usable again.

Merging!!
Thanks for your effort :muscle:

2024-11-20 18:23 UTC, merged