Add 'Voucher:' before voucher code on order confirmation emails
openfoodfoundation/openfoodnetwork pull request #12998
Opened 2024-11-26 09:14 UTC by kernal053

#### What? Why?

- Closes #12978

#### What should we test?

- When voucher is used in an order as a shopper, order confirmation email will contain "Voucher:" text before voucher code.
- Check also for translated "Voucher" text.

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [x] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

#### Dependencies

#### Documentation updates

2024-11-29 02:55 UTC, mkllnk requested changes
Nice! Thank you.

I have a suggestion below. Are you up for that?

2024-11-29 02:55 UTC, mkllnk commented on app/views/spree/order_mailer/_order_summary.html.haml
>            = "#{adjustment.label}:"
May I suggest to use a translation here? Then we can customise the display for each language. Other possibilities could be:

* Voucher CODE:
* CODE (voucher):
* CODE (discount):

You can pass the voucher code to the translation:
```suggestion
          - if adjustment.originator_type == "Voucher"
            = t(".voucher_label", code: adjustment.label)
```

And in `en.yml` I would add "Voucher %{code}:" as translation, avoiding the weird double colon in the line.

2024-12-04 22:24 UTC, dacook requested changes
Thanks, that's a good solution.

But actually we prefer not to change all the locale files, only `en.yml`. All other files are managed with Transifex and shouldn't be updated directly, so this could cause conflicts. Could you please remove those changes?

For reference:
https://github.com/openfoodfoundation/openfoodnetwork/wiki/Internationalisation-%28i18n%29#development

2024-12-08 23:30 UTC, rioug approved these changes
Nice one :+1: Thanks @kernal053 :pray:

2024-12-08 23:32 UTC, dacook approved these changes
Thankyou!

2024-12-08 23:43 UTC, dacook requested changes
Hmm, sorry I didn't notice this earlier, but this will hide any adjustments that are not of type "Voucher". 
I'm not sure, but I think other adjustments such as [Enterprise Fees](https://guide.openfoodnetwork.org/basic-features/shopfront/enterprise-fees) or tax might appear here.

If so, it would be worth adding a spec here: https://guide.openfoodnetwork.org/basic-features/shopfront/enterprise-fees

Are you willing to look into this?

2024-12-09 09:25 UTC, kernal053 commented
Apologies, I overlook other adjustments. Will fix the code. Right now, we're only excluding `LineItem` adjustable. Thereby, not displaying enterprise fees. 

And adding spec, I think `order_mailer_spec.rb` needs to be updated. I couldn't get around your message regarding it. I guess you meant to mention specific spec file.

2024-12-09 22:03 UTC, dacook commented
Thanks for looking back into this.

> And adding spec, I think `order_mailer_spec.rb` needs to be updated. I couldn't get around your message regarding it. I guess you meant to mention specific spec file.

I'm sorry, I pasted the wrong link. You're right, it was meant to be a link to `order_mailer_spec.rb` 👍

2024-12-10 22:26 UTC, rioug approved these changes
Looks good, thanks @kernal053 :pray:

2024-12-10 22:36 UTC, dacook approved these changes
Great!

2024-12-10 22:36 UTC, dacook commented on spec/mailers/order_mailer_spec.rb
> +      expect(cancellation_email.body).to include("Shipping:")
I see that the shipping fee comes from the factory order_with_totals_and_distribution. Maybe it's worth a comment here explaining that, but never mind :)

2025-01-03 13:01 UTC, drummer83 commented
Hi @kernal053,
Thank you so much for working on this. Due to the holiday season it took a while until we got to testing it - I'm sorry for that.

I've tested your PR now and here are the results.

| Tested page | |
| - | - |
| Order summary page | |
| Before: ![grafik](https://github.com/user-attachments/assets/c82c875b-3962-43b2-8a5c-0694cb0f7127) | After: ![grafik](https://github.com/user-attachments/assets/cb30339a-0fa3-4dd5-befe-70a3dc0ecb12) |
| Edit cart page | |
| Before: ![grafik](https://github.com/user-attachments/assets/c96ec671-137d-4241-ac11-21428351cf7f) | After: ![grafik](https://github.com/user-attachments/assets/b9d62a37-e06e-42db-999f-6b37d55f3ea3) |
| Order confirmation page | |
| Before: ![grafik](https://github.com/user-attachments/assets/3990408b-51b9-4c7b-98b0-dd0d30a19c47) | After: ![grafik](https://github.com/user-attachments/assets/ac50e310-9728-4d29-b22a-4461b2bd0124) |
| Order confirmation email | |
| Before: ![grafik](https://github.com/user-attachments/assets/2fd82323-d27c-4312-a3ba-033c4b7d58fd) | After: ![grafik](https://github.com/user-attachments/assets/4916a633-576a-4de8-a9ce-f55b7e8bd567) |

## Results
A few things are worth mentioning.
- As expected, the order confirmation email is now including the 'Voucher' prefix. :tada: :muscle: Excellent!
- We can see that the format is slightly different to what was specified and what is used in other places. Instead of a colon we have brackets here now. It's a minor issue, not blocking the merging of your PR.
- We can see that we are still missing the 'Voucher:' prefix on the edit cart page. This is out of scope for this issue, so also no block for merging your PR.

## Summary
Your PR is solving the issue well. I will open new issues to address the remaining two minor things I've found. If you like, feel free to tackle them as well.

Thank you so much again! :pray: 
Merging! :partying_face: :rocket:

2025-01-03 13:01 UTC, merged