Calculate stock from DFC wholesale variants
openfoodfoundation/openfoodnetwork pull request #13049
Opened 2024-12-20 04:37 UTC by mkllnk

#### What? Why?

- Closes #12928 

When importing DFC products, two products can be coupled as retail variant and wholesale variant of the same product. We aim to sell the retail variant through an OFN shop and then place backorders for the wholesale variant to make use of economies of scale.

We already calculated the price of a retail variant from its wholesale variant:

* #13033

Now we also calculate the stock level from the wholesale variant.

#### What should we test?

- Import a DFC catalog at Admin -> Product Import
- Observe the product prices and stock levels.
- Add retail products to an order cycle.
- Change stock levels in Shopify.
- Add a retail variant to your OFN cart.
- The stock level should get updated correctly.

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [x] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

#### Dependencies

#### Documentation updates

2025-01-02 04:25 UTC, dacook requested changes
Great work, easy to follow the commits and see how the code evolves.

Just one little hiccup at the end:

2025-01-02 04:25 UTC, dacook commented on engines/dfc_provider/app/services/dfc_catalog.rb
> +    offer.stockLimiation = wholesale_offer.stockLimitation.to_i * transformation.factor
Hmm, that spelling doesn't look right:

```suggestion
    offer.stockLimitation = wholesale_offer.stockLimitation.to_i * transformation.factor
```

The test below isn't testing for this. Is it something that can be tested?

2025-01-02 05:50 UTC, mkllnk commented on engines/dfc_provider/app/services/dfc_catalog.rb
> +    offer.stockLimiation = wholesale_offer.stockLimitation.to_i * transformation.factor
Well spotted!

While the standard allows a stock limitation on catalog items and offers, the FDC data stores the stock only on the catalog item and not the offer. So this code path didn't run. I added a test case for that now.

2025-01-02 05:58 UTC, dacook approved these changes
👏

2025-01-05 23:52 UTC, rioug approved these changes
Looks good :+1:

2025-01-05 23:53 UTC, rioug commented
@mkllnk I'll let you handle the conflict

2025-01-07 06:20 UTC, dacook commented
Initial issues: 

## 1. Session error causes 500 page
With no explanation of what's wrong. Eg: https://staging.openfoodnetwork.org.uk/admin/dfc_product_imports?enterprise_id=203921&catalog_url=https%3A%2F%2Fenv-0105831.jcloud-ver-jpe.ik-server.com%2Fapi%2Fdfc%2FEnterprises%2Ftest-hodmedod%2FSuppliedProducts&commit=Import

Bugsnag reveals [Rack::OAuth2::Client::Error - invalid_grant :: Session not active](https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/66e89c5fdf0c335670df0dd3?filters[event.since]=30d)

## 2. OIDC settings page says it is active, when it is not.
https://staging.openfoodnetwork.org.uk/admin/oidc_settings

Maybe when we load the page it should perform a check to display current status.
Workaround: disconnect and reconnect.

2025-01-07 22:29 UTC, mkllnk commented
The first issue you found is on our list to fix:

*  #12987

Currently, @rioug is assigned. But who has time first?

2025-01-07 22:46 UTC, rioug commented
> Currently, @rioug is assigned. But who has time first?

Go for it !

2025-01-07 23:00 UTC, dacook commented
## Testing

- [x] Import a DFC catalog at Admin -> Product Import: https://env-0105831.jcloud-ver-jpe.ik-server.com/api/dfc/Enterprises/test-hodmedod/SuppliedProducts
- [x] Observe the product prices and stock levels.
    Case 60x40mL has 4 in stock
    ![Screenshot 2025-01-08 at 9 43 18 am](https://github.com/user-attachments/assets/4502fc3f-de0a-44bd-aab9-5d6ee4ec4bec)
- [x] Add retail products to an order cycle.
- [x] Change stock levels in Shopify.
    Case 60x40mL now has 5 in stock
    <img width="630" alt="Screenshot 2025-01-08 at 9 43 44 am" src="https://github.com/user-attachments/assets/da41a96e-1184-464d-aac8-8a0063d7b77d" />
- [x] Add a retail variant to your OFN cart.
    Checked out 2x 40mL bottles
    ![Screenshot 2025-01-08 at 9 48 10 am](https://github.com/user-attachments/assets/2f3d2340-f472-415d-ae28-a3800cbfdd12)
- [x] The stock level should get updated correctly.
    OFN now shows 5 cases available. 5 cases = 30 bottles. 2 are sold, so 28 remaining bottles available.
    ![Screenshot 2025-01-08 at 9 49 50 am](https://github.com/user-attachments/assets/92295ce2-b8bc-480c-802f-868ac3e43ce7)

✅ Ok I think that's correct! Look right to you @mkllnk ?

## Other notes
### Price
30.20 / 6 = 5.0333333
This makes pricing fully transparent, and the hub would cover their processing costs with enterprise fees in OFN 👍 

### Product amounts
Product amounts show as weight instead of volume. I can see that Shopify only supports weight (assumed gross weight for shipping, not the net product weight), so that's the best we can do I guess. Unless we were to use a metafield or some other shopify plugin.
<img width="344" alt="Screenshot 2025-01-08 at 9 55 06 am" src="https://github.com/user-attachments/assets/a384d13f-2c48-4211-b221-0055fbbb809b" />

2025-01-08 01:32 UTC, mkllnk commented
> Ok I think that's correct! Look right to you @mkllnk ?

Yes, looking good. Thank you! I'll merge then.

2025-01-08 01:32 UTC, merged

2025-01-08 07:35 UTC, RaggedStaff commented
> I also played around with updating values in OFN bulk edit products screen, and found that these changes aren't reflected back in Shopify.
> A re-import resets the wholesale product stock.

I think that's probably how we want it for now...  Shopify is managing the wholesale variant stock,  OFN is managing the retail variant stock  Syncromising stock updates across multiple locations would be a lot more complex to manage. 

That said...  we do have local stock of the retail variant,  so a check to make sure that doesn't reset on refresh might be handy? 

Also worth checking how cancellations are handled: stock should be returned to the retail variant, and (where possible) the back order reduced (& local stock readjusted down).

2025-01-09 22:37 UTC, dacook commented
> Also worth checking how cancellations are handled: stock should be returned to the retail variant, and (where possible) the back order reduced (& local stock readjusted down).


Good idea. I cancelled an order:
![Screenshot 2025-01-10 at 9 26 21 am](https://github.com/user-attachments/assets/0f51a246-156c-4209-94b1-0aca09f244d7)

I didn't check the stock beforehand, but  the other day there were 28 bottles in stock.
Now cases are 0, and there's only the 2 cancelled bottles. Is this because the backorder was automatically adjusted down to only order what's needed?
![Screenshot 2025-01-10 at 9 29 34 am](https://github.com/user-attachments/assets/b207b1b0-5841-409f-b318-50558f401007)

I found the backorder, which is empty:
![Screenshot 2025-01-10 at 9 33 47 am](https://github.com/user-attachments/assets/d3dd8762-1c23-44c2-8840-f81e70c25a95)

2025-01-10 00:06 UTC, mkllnk commented
I'm not sure I have the full picture here. But yes, when orders are cancelled, the backorder is adjusted. And if we then don't need to order anything then the backorder ends up being empty.

2025-01-10 00:06 UTC, mkllnk commented
The test shop is used in various ways. So I don't think that you can refer to stock levels from a few days ago.