Hide stripe during payment method creation
openfoodfoundation/openfoodnetwork pull request #6026
Opened 2020-09-14 23:38 UTC by andrewpbrett

Hide stripe in payment method creation if no enterprises have set up stripe connect. 

Addresses (and maybe completely solves) #4713 

#### What? Why?

Closes #4713, if we decide it's sufficient. 

If I understand the issue correctly, we'd like to not allow people to create a payment method that uses Stripe if they haven't set up Stripe connect. The 500 error looks like it was addressed already in https://github.com/openfoodfoundation/openfoodnetwork/pull/4758. This goes further and hides the Stripe methods from the drop down during payment method creation. 

We could go further and validate based on which enterprises the payment method is being added to; for example, if one out of four enterprises that a user manages has Stripe Connect set up, the option will appear in the drop down. The user could then choose it, and select an enterprise that *doesn't* have it set up. We could try catching this case as well if it seems like it would have sufficient impact. 

We could also go further and include a link below the drop down if the Stripe options are not shown, explaining why they're not shown and giving the user a link to connect to Stripe. 

#### What should we test?
With an enterprise that doesn't have Stripe connected, create a new payment method. The drop down for Provider should not have Stripe providers as an option. 

#### Release notes
Only show Stripe as a provider during payment method creation if Stripe Connect has been configured. 

Changelog Category: Changed

#### Discourse thread
#### Dependencies
#### Documentation updates

2020-09-17 12:12 UTC, luisramos0 commented
I like the section you are adding to your PRs: "We could go further and"
To make it more clear this could be a separate section in the PR :+1:

2020-09-17 12:15 UTC, luisramos0 requested changes
I dont think this PR is correct.
If the a stripe account is not setup the hub will see the useful "connect one" button to go and do it. I think that should remain.

To improve the state I think what we need is to validate the data on saving the payment method and issue an error if the method is stripe and the stripe credentials are not present.

2020-09-18 01:24 UTC, andrewpbrett commented
I think the database validation is a good idea. This PR removes it from the dropdown so it would be pretty difficult for the method to be set to Stripe in the first place (before the payment method is even saved). Also the Connect Stripe button would still be present, all we're hiding is the dropdown. 

Sorry if I'm repeating what you already understand! I just wasn't sure based on your comment if it was clear what this does.

2020-09-18 13:41 UTC, luisramos0 commented
hmmm, I dont think we are seeing the same thing, if you remove stripe from the options this will not be possible:
![image](https://user-images.githubusercontent.com/1640378/93604244-07031880-f9bd-11ea-87d3-14cd8607914c.png)

2020-09-18 13:59 UTC, andrewpbrett commented
Ohhh okay. You are totally right, a picture is worth a thousand words. I'm going to close this PR then and just create a new one that does the backend validation.

2020-09-18 13:59 UTC, closed without merging