Added Bash scripts for logging the long screen output of routine tasks
openfoodfoundation/openfoodnetwork pull request #6054
Opened 2020-09-18 23:38 UTC by jhsu802701

The nuke.sh and nukec.sh scripts are for cleaning up all Docker images and containers.  This makes a fresh start possible, which is necessary for making sure that the setup procedure is comprehensive and isn't out-of-date.

Some routine tasks (especially testing) produce a flood of screen output.  I've added other Bash scripts for executing these tasks AND logging the screen output.  I find these logs to be necessary for troubleshooting and debugging.

2020-09-19 18:28 UTC, luisramos0 requested changes
Interesting PR, thanks!

I like this generally.
I dont think we should put these scripts at the root of the project though.
Maybe move all these to script/docker ?

2020-09-19 19:57 UTC, jhsu802701 commented
I could create a bin directory and put scripts there.  (An example of this approach is at https://github.com/codebar/planner.)

2020-09-19 19:57 UTC, closed without merging

2020-09-20 18:40 UTC, luisramos0 commented
I think script is good enough, in my mind bin would be for scripts that run the app and change the app runtime.
I wonder what other devs think? @openfoodfoundation/developers

2020-09-23 02:30 UTC, mkllnk commented
The [Rails guide](https://guides.rubyonrails.org/getting_started.html#creating-the-blog-application) mentions the bin directory:

> Contains the rails script that starts your app and can contain other scripts you use to setup, update, deploy, or run your application.

It doesn't mention a script directory. I think that script got renamed to bin in Rails 4. Docker scripts can be part of "setup... or run your application". I would be happy with scripts like this going to `bin/docker/` but the scripts in this PR would need some work to make them safe and easy to use for the broader community (we don't want to accidentally run nuke on a production server).