Replace `create` with `build_stubbed` in address model specs
openfoodfoundation/openfoodnetwork pull request #6065
Opened 2020-09-21 01:35 UTC by arku

#### What? Why?

Related to https://github.com/openfoodfoundation/openfoodnetwork/issues/6062

We don't need objects in the database for the unit tests most of the times. This PR replaces `FactoryBot::Syntax::Methods#create` calls with `FactoryBot::Syntax::Methods#build_stubbed` in the `Address` model specs wherever possible.

#### What should we test?

#### Release notes

Changelog Category: Added | Changed | Deprecated | Removed | Fixed | Security

#### Discourse thread

#### Dependencies

#### Documentation updates

2020-09-21 05:05 UTC, arku commented
This is weird. The model specs pass locally 😕

2020-09-21 11:36 UTC, luisramos0 commented
ah, yes, there's something I cant understand with this spec. I struggled here recently when moving some code from spree.
Maybe we can leave it as is for now.

2020-09-24 17:44 UTC, luisramos0 requested changes
something funny with this address spec... the build is broken.

2020-09-26 20:18 UTC, luisramos0 approved these changes
nice catch :clap: :clap: :clap:

2020-09-26 20:19 UTC, merged