Add new translation for shipping method
openfoodfoundation/openfoodnetwork pull request #6246
Opened 2020-10-24 07:33 UTC by tsara27

What? Why?
Closes #5993

I am adding `spree.shipping_method` translation. The issue was caused by missing the translation key on the locales. 

What should we test?
Test the edit shipping method on order details on admin dashboard.

How to do:

1. Login as an admin.
2. Go to orders.
3. Select one of the orders and edit shipping method.

Changelog Category: Fixed

2020-10-24 09:32 UTC, luisramos0 requested changes
I dont think we should test translations like this.
Also, this page is already verified in spec/features/admin/order_spec.rb.
imo this PR should only add the translation key.

2020-10-24 09:44 UTC, tsara27 commented
> I dont think we should test translations like this.
> Also, this page is already verified in spec/features/admin/order_spec.rb.
> imo this PR should only add the translation key.

Hello @luisramos0 ,

I'll fix it. Thanks!

2020-10-24 21:12 UTC, Matt-Yorkley approved these changes
Great, thanks @tsara27 :smile:

2020-10-25 20:12 UTC, luisramos0 approved these changes

2020-10-26 04:17 UTC, tsara27 commented
> Great, thanks @tsara27

No worries! :slightly_smiling_face:

2020-10-28 23:19 UTC, filipefurtad0 commented
Hello @tsara27 ,

The page renders correctly, the introduced key should work :+1: 

![image](https://user-images.githubusercontent.com/49817236/97506522-07ef7880-1973-11eb-8062-67ef13d337cc.png)

Thank you for this contribution!

2020-10-28 23:25 UTC, tsara27 commented
> Hello @tsara27 ,
> 
> The page renders correctly, the introduced key should work 
> 
> ![image](https://user-images.githubusercontent.com/49817236/97506522-07ef7880-1973-11eb-8062-67ef13d337cc.png)
> 
> Thank you for this contribution!

Hello @filipefurtad0 

Glad it works! I am so happy that I could contribute to this project.

2020-10-29 00:09 UTC, merged