Corrected RuboCop offenses in spec/support/request/shop_workflow.rb
openfoodfoundation/openfoodnetwork pull request #6253
Opened 2020-10-26 15:36 UTC by jhsu802701

This pull request corrects the following RuboCop offenses:
```bash
spec/support/request/shop_workflow.rb:1:1: C: Metrics/ModuleLength: Module has too many lines. [101/100]
module ShopWorkflow ...
^^^^^^^^^^^^^^^^^^^
spec/support/request/shop_workflow.rb:74:34: W: Lint/UnusedMethodArgument: Unused method argument - variant. If it's necessary, use _ or _variant as an argument name to indicate that it won't be used.
  def click_add_bulk_max_to_cart(variant = nil, quantity = 1)
```

This pull request reduces the number of offenses from 117 to 115.

2020-10-28 17:02 UTC, sauloperez commented
Hi @jhsu802701 ! there have been recent changes on that `ModuleLength` cop and you'll need to rebase to solve the conflicts.

2020-10-28 21:12 UTC, luisramos0 requested changes
Thanks @jhsu802701 
Please see comments below.

2020-10-29 05:18 UTC, closed without merging

2020-10-29 13:34 UTC, luisramos0 commented on spec/support/request/shop_workflow.rb
> +  def click_add_bulk_max_to_cart(_variant = nil, quantity = 1)
hey  @jhsu802701 this change here is still relevant, let's get this in!

2020-10-29 13:37 UTC, luisramos0 commented on spec/support/request/shop_workflow.rb
> +  def click_add_bulk_max_to_cart(_variant = nil, quantity = 1)
ah, I see you have created another branch and PR. Do you know you can easily do it in the same PR? All you need is to fetch/refresh master and then on this branch run "git rebase master". aybe you can try that next time :+1: