fixed capture payment
openfoodfoundation/openfoodnetwork pull request #6506
Opened 2020-12-10 00:13 UTC by nikhilt99

#### Listing Orders UX Improvement: Payment state of canceled cash/EFFs order
This fix will get rid of the capture payment button presented in the listing orders table when the state of an order is cancelled. This is important because no money is due when an order is cancelled.

Closes #5268 

Customer opts to pay for an order by cash/EFFs payment method. This order is then cancelled- either by the food enterprise or the customer- prior to payment being captured. If an order is then cancelled, the capture payment should disappear from the listing orders table. The current behavior has the capture payment button as still present.

One can test if when an order is made by cash and is cancelled before a payment is captured, does the "capture payment" button still exist for that order. This involves many functional tests and more rigorous testing may be required for the UI.

#### Release notes
For cancelled orders by cash/EFF's payment method before payment is captured, capture payment button is deleted 

User facing changes

2020-12-10 08:58 UTC, luisramos0 commented on app/serializers/api/admin/order_serializer.rb
> +        object.payment_required? && pending_payment && (order.state != "canceled")
Hello, I think it's better if you use the helper method:
!order.canceled?

2020-12-10 08:58 UTC, luisramos0 commented on app/serializers/api/admin/order_serializer.rb
> +        object.payment_required? && pending_payment && (order.state != "canceled")
```suggestion
        object.payment_required? && pending_payment && !order.canceled?
```

2020-12-11 11:48 UTC, Matt-Yorkley requested changes
Looks good, but there's a few broken specs in the build that look they would need a bit of adapting before we could merge this. Moving back to `in dev` for now.

2021-01-22 08:11 UTC, RachL commented
hello @nikhilt99 hope this message finds you well. Are you still available to work on the required changes?

2021-04-16 10:42 UTC, RachL commented
As decided during delivery circle : we are not going to be able to finish this PR. Closing.

2021-04-16 10:42 UTC, closed without merging