Products endpoint content type
openfoodfoundation/openfoodnetwork pull request #6578
Opened 2020-12-30 12:58 UTC by Matt-Yorkley

#### What? Why?

WIP

Closes #[the issue number this PR is related to]

#### What should we test?

#### Release notes

Changelog Category: User facing changes | Technical changes

#### Dependencies

#### Documentation updates

2021-01-02 01:31 UTC, andrewpbrett approved these changes

2021-01-06 12:30 UTC, Matt-Yorkley commented
@andrewpbrett I've updated the PR a bit and added a regression test for the bug. It was failing, but it's fixed now.

2021-01-06 17:10 UTC, andrewpbrett approved these changes
Looks great! 💪

2021-01-08 11:51 UTC, sauloperez requested changes

2021-01-08 11:51 UTC, sauloperez commented on spec/controllers/api/order_cycles_controller_spec.rb
> +          allow_any_instance_of(OrderCycle).to receive(:open?) { false }
See https://github.com/openfoodfoundation/openfoodnetwork/pull/6534#discussion_r553881544

2021-01-08 13:09 UTC, Matt-Yorkley commented on spec/controllers/api/order_cycles_controller_spec.rb
> +          allow_any_instance_of(OrderCycle).to receive(:open?) { false }
Done :ok_hand:

2021-01-08 16:58 UTC, sauloperez approved these changes

2021-01-08 16:59 UTC, sauloperez commented
This looks like a no-test to me. So we could merge right after rebasing and getting a :green_apple: build.

2021-01-09 01:34 UTC, merged