Improve performance on summing adjustments and payment
openfoodfoundation/openfoodnetwork pull request #6655
Opened 2021-01-13 16:18 UTC by Matt-Yorkley

#### What? Why?

`:amount` is a database field in these cases, as opposed to a method that returns a computed result. Calling `.sum(:amount)` is much more efficient as it computes the sum at database level, as opposed to `.map(&:amount).sum`, which would fetch and instanciate all the objects first, and then sum the amounts after.

#### What should we test?

Green build.

#### Release notes

Improved performance on summing payment and adjustment amounts.

Changelog Category: Technical changes

2021-01-14 23:27 UTC, mkllnk requested changes
Nice! This should really speed things up. I found one case though where we have an array and can't do this.

2021-01-14 23:27 UTC, mkllnk commented on app/helpers/checkout_helper.rb
> +        label: I18n.t(:orders_form_admin), amount: enterprise_fee_adjustments.sum(:amount)
I think that your assumption of having an AR relation isn't correct here. `adjustments` are an array and `enterprise_fee_adjustments` are an array, too. You can simplify this though:
```suggestion
        label: I18n.t(:orders_form_admin), amount: enterprise_fee_adjustments.sum(&:amount)
```

2021-01-14 23:30 UTC, mkllnk commented
> What should we test?
> 
> Green build.

Is that a new strategy? It's probably good to take some load off our testers but it looks like our code coverage isn't quite good enough for this. Did I miss a discussion here?

2021-01-15 17:29 UTC, Matt-Yorkley commented
Nice catch @mkllnk !

> Is that a new strategy?

Not in general, but I've been doing it for very small changes that seem to be covered by specs. I missed this one :see_no_evil:

2021-01-18 21:22 UTC, mkllnk approved these changes

2021-01-19 14:48 UTC, sauloperez approved these changes

2021-01-21 11:34 UTC, filipefurtad0 commented
Hey @Matt-Yorkley ,

Quite a noticeable improvement :tada: 

Clicking "Update and Recalculate Fees" on this bulky order:

Before:
![image](https://user-images.githubusercontent.com/49817236/105345552-514f0d00-5bdc-11eb-9a6c-f3cf15c489d3.png)

After:
![image](https://user-images.githubusercontent.com/49817236/105345617-5f9d2900-5bdc-11eb-99a3-cfcee8e0f223.png)

The values match, ready to go.

2021-01-21 11:38 UTC, sauloperez commented
wow! :tada:

2021-01-21 12:32 UTC, Matt-Yorkley commented
`9.37 seconds -> 3.12 seconds`

Hot stuff, that's a ~67% reduction! I didn't realise the impact would be that big. There should be multiple places in the app where we get this kind of boost.

:tada: :smile:

2021-01-21 18:58 UTC, merged