Change on_hand's field to number_field and add required attribute on new products form
openfoodfoundation/openfoodnetwork pull request #6861
Opened 2021-02-10 20:56 UTC by ccozkan

#### What? Why?

Closes [#6159 ](https://github.com/openfoodfoundation/openfoodnetwork/issues/6159)

Even though original issue suggests showing "on hand is a mandatory field" errors using model validations, I believe this would add more complexity, when same trouble can be solved with more simple way.

Default value of `count_on_hand` is defined as `0` in database level, therefore `StockItem` with nil `count_on_hand` will be build as `0`. In order to detect the violence of presence validation,  we would need to add another migration(which removes default value of `count_on_hand` on `StockItem`), and add custom associated validation to `Product` model for checking validity of the `StockItem`. And also maybe some changes would be needed regarding `concerns/variant_stock#save_stock`.

This PR suggests adding html required attribute to 'on hand' field, and changing it is type from `text_field` to `number_field`, since it is an integer column.

#### What should we test?
* Adding new product on `admin/products/new` with deleting 'on hand' field value. HTML required attribute should point that box can not be left blank. 
* On hand value can be increased and decreased by clicking its up/down arrows on the field box.

#### Release notes

Change on_hand's field to number_field and add required attribute on new products form

User facing changes

2021-02-15 18:28 UTC, andrewpbrett requested changes
Thanks for the contribution here @ccozkan. Sorry if I'm misunderstanding something here; I read through the issue and it looks like it's changed quite a bit over time. In my opinion we should actually just remove the `*` that indicates this field is required, since that matches the backend behavior most closely. 

The `required` attribute isn't 100% reliable (e.g. if we change the form in the future to rely on javascript instead of a regular post request) and making it a number field will have different effects in different browsers. So I think removing the `*` is probably the simplest thing to do here.

2021-02-15 22:04 UTC, andrewpbrett approved these changes
Thanks @ccozkan !

2021-02-17 16:23 UTC, filipefurtad0 commented
Hey @ccozkan ,

Before staging this PR we had this situation, when creating a product and leaving mandatory fields blank:

![image](https://user-images.githubusercontent.com/49817236/108233814-0a512a80-713c-11eb-8ad2-8d11b95cd37b.png)

And after this PR we can check the asterisk is gone:

![image](https://user-images.githubusercontent.com/49817236/108234068-58662e00-713c-11eb-9a88-885c35698e05.png)

We're good to go here.

2021-02-17 19:10 UTC, ccozkan commented
Thank you too! It's been a good experience for me🙌

2021-02-18 11:39 UTC, merged