Fix #6949: Add default icon value if enterprise.category is nil
openfoodfoundation/openfoodnetwork pull request #6950
Opened 2021-02-23 19:47 UTC by andrewpbrett

#### What? Why?

Closes #6949 

This protects against a nil value when looking up the icon to display for an enterprise.

#### What should we test?

None/green build.

#### Release notes

Fixed a bug that would cause an shop's icon to not appear on the group map. 

Changelog Category: User facing changes 

#### Dependencies

#### Documentation updates

2021-02-24 09:46 UTC, sauloperez approved these changes

2021-02-24 09:47 UTC, sauloperez requested changes
This should be unit tested IMO as the behavior has changed

2021-02-25 01:24 UTC, mkllnk approved these changes
Nice! :smile: 

Just a process thing: I think when you addressed the comments of a reviewer and put it back to review, it's good to re-request their review. Then we see that a review is pending (instead of changes requested) and the reviewer gets notified. I'll do that with Pau now.

2021-02-25 07:58 UTC, sauloperez approved these changes

2021-02-25 12:20 UTC, merged