Add resumed to list of allowable order states to view the payment tab
openfoodfoundation/openfoodnetwork pull request #7014
Opened 2021-03-04 19:26 UTC by andrewpbrett

#### What? Why?

Closes #7011

This adds "resumed" to the list of states that an order can be in. 

#### What should we test?

Visiting the payments tab on a resumed order.

#### Release notes

Fixed a bug where orders in the Resumed state could not access the payments tab.

Changelog Category: User facing changes

#### Dependencies

#### Documentation updates

2021-03-04 19:28 UTC, andrewpbrett reviewed
I considered pulling this into a separate method, potentially on `Order`, but I think it belongs in the controller, and it's already in a private method that describes what it's checking for... so I left it :)

2021-03-08 14:14 UTC, sauloperez requested changes
This requires a test IMO. At some point, we'll have to slim down this controller and when that happens, we'll want to be covered by tests.

2021-03-08 18:26 UTC, Matt-Yorkley approved these changes

2021-03-08 21:16 UTC, sauloperez approved these changes

2021-03-17 17:46 UTC, filipefurtad0 commented
Hey @andrewpbrett ,

Tested accessing the Payments tab, after:
- cancelling an order - OK
- after resuming the order  - OK

Thanks for this fix - this works now :tada

2021-03-17 17:46 UTC, merged