Only show primary producers on shopfront list of producers (fix #4218)
openfoodfoundation/openfoodnetwork pull request #7015
Opened 2021-03-04 22:36 UTC by andrewpbrett

#### What? Why?

Closes #4218

This limits the list of producers on the shopfront Producers tab to those enterprises who are primary producers; that is, it does not show hub-only enterprises.

#### What should we test?

Enterprises that are hubs and not primary producers should not show up on that tab for a hub. 

#### Release notes

Fixed a bug where non-producing enterprises would show up on the shopfront's list of producers.

Changelog Category: User facing changes

#### Dependencies

#### Documentation updates

2021-03-08 14:20 UTC, sauloperez requested changes
I'm missing at least a unit test (an additional integration test would also be helpful though) to ensure we don't break it in the future.

2021-03-08 18:35 UTC, Matt-Yorkley approved these changes

2021-03-08 21:17 UTC, sauloperez approved these changes

2021-03-17 21:02 UTC, filipefurtad0 commented
Hey @andrewpbrett ,

Before this PR:

![image](https://user-images.githubusercontent.com/49817236/111537723-b39f3680-8763-11eb-8011-691bf3e3361e.png)

The Hacienda and Hacienda Distributors are not producers (both are hubs); **After this PR** these are gone:

![image](https://user-images.githubusercontent.com/49817236/111537795-c9146080-8763-11eb-94c9-22c9c49abaf6.png)

Cool, thanks for this fix! Good to go :+1:

2021-03-17 22:30 UTC, merged