Remove UI for modifying line items on canceled orders
openfoodfoundation/openfoodnetwork pull request #7228
Opened 2021-03-25 23:59 UTC by andrewpbrett

#### What? Why?

Closes https://github.com/openfoodfoundation/openfoodnetwork/issues/7165 

This removes the UI for modifying line item quantities if the order is canceled. This prevents* the order total from being modified and will also address #7166. 

*prevents unless the admin edit order page is also open in another tab (hopefully a very rare scenario). @mkllnk is writing a PR to address preventing the request from being processed on the backend in that case. We're going to attach Maikel's PR to #7166. 

#### What should we test?

Cancel an order. The admin edit order page should no longer allow adding/editing line items for the order. 

#### Release notes

Fixed a bug where canceled orders could be modified, leading to discrepancies in customer balances and stock levels. 

Changelog Category: User facing changes

#### Dependencies

#### Documentation updates

2021-03-26 00:01 UTC, andrewpbrett commented
Once this and @mkllnk's PR are merged I think we can close https://github.com/openfoodfoundation/openfoodnetwork/issues/7164

2021-03-26 01:43 UTC, mkllnk reviewed
Great!

2021-03-26 01:43 UTC, mkllnk commented on app/views/spree/admin/orders/_add_product.html.haml
> +      = Spree.t(:cannot_add_item_to_canceled_order)
I think that we should use away from the `Spree.t` method and use lazy lookup instead.
```suggestion
      = t(".cannot_add_item_to_canceled_order")
```
https://github.com/openfoodfoundation/openfoodnetwork/wiki/Internationalisation-%28i18n%29#development

2021-03-26 01:43 UTC, mkllnk commented on app/views/spree/admin/orders/_add_product.html.haml
> +      = Spree.t(:cannot_add_item_to_canceled_order)
I'm wondering here though if we should just take out the whole section. We think that nobody needs to change a cancelled order and therefore we don't need to tell people that they can't. Nobody would think of doing it.

Providing a screenshot of your change is always helpful.

2021-03-26 16:36 UTC, andrewpbrett commented
> I'm wondering here though if we should just take out the whole section.

I was getting a strange rendering error when I took it out entirely, so I went with the most expedient solution rather than digging into it much more. 

> Providing a screenshot of your change is always helpful.

Done!

2021-03-26 16:55 UTC, Matt-Yorkley approved these changes
:+1:

2021-03-29 05:37 UTC, mkllnk requested changes

2021-03-29 05:37 UTC, mkllnk commented on app/views/spree/admin/orders/_add_product.html.haml
> +      = t(".cannot_add_item_to_canceled_order")
If you change this, you also have to change `en.yml`.

We really need to raise errors in feature specs if a translation can't be found...

2021-03-29 06:02 UTC, mkllnk approved these changes

2021-03-29 12:24 UTC, filipefurtad0 commented
Hey @andrewpbrett ,

Thanks for picking this up :+1: 

After staging, it's possible to verify that the UI does not allow for changes in:
- line item quantities
- adding/removing a line item
- changing shipping methods
This prevents changing the order total and the reported discrepancies:

![image](https://user-images.githubusercontent.com/49817236/112836102-0d6ffc80-9092-11eb-90b8-2b4be91d3064.png)

Still to do:
- disabling Adjustments (adding/deleting/editing): this tab is active and can still change the order total, after cancelling the order
- as Maikel points out, the missing entry on `en.yml` for the new string causes a missing translation


This PR is already a great improvement so let's merge it :+1:

2021-03-29 13:24 UTC, merged

2021-03-29 22:54 UTC, mkllnk commented
> as Maikel points out, the missing entry on en.yml for the new string causes a missing translation

Uh, I thought I fixed that with my additional commit. :thinking:

2021-03-30 09:33 UTC, filipefurtad0 commented
Oh, I missed that one @mkllnk - thanks :+1: 

I just opened #7279 on the other item, but I see you already have a PR on the way @andrewpbrett :ok_hand:  I've linked it to your PR.