Never return 0 for a denominator
openfoodfoundation/openfoodnetwork pull request #7332
Opened 2021-04-06 22:49 UTC by andrewpbrett

#### What? Why?

Closes #[the issue number this PR is related to]

#### What should we test?

#### Release notes

Changelog Category: User facing changes | Technical changes

#### Dependencies

#### Documentation updates

2021-04-14 09:35 UTC, sauloperez requested changes
I think I still worth covering 

> A variant with a unit value of 0 should display a unit price instead of NaN

with a integration-like test like a feature spec. As far as I see we only check that at unit level.

2021-04-14 17:03 UTC, andrewpbrett commented
> I think I still worth covering with a integration-like test like a feature spec

I'm not sure I agree, given what we're doing in https://github.com/openfoodfoundation/openfoodnetwork/pull/7412 - writing a feature spec for a case that should never actually happen feels like it's adding unnecessarily to the build time.

2021-04-15 06:26 UTC, sauloperez commented
Fair enough but aren't we adding defensive coding for something that won't happen anymore when we merge #7412 then?

2021-04-15 14:44 UTC, andrewpbrett commented
Excellent point 😁 I think when I started this I didn't think that #7412 would be so extensive, but you're right, this PR is probably now entirely unnecessarily defensive.... but there is something that feels wrong about not checking for the possibility that a method called `denominator` returns zero.

2021-04-15 15:55 UTC, sauloperez commented
If that makes you feel better, it doesn't add too much complexity but again... science; it can't happen :joy:

2021-04-15 15:56 UTC, sauloperez approved these changes

2021-04-15 16:52 UTC, andrewpbrett commented
Let's just close it actually. Trust the database to enforce and fail loudly if something goes wrong.

2021-04-15 16:52 UTC, closed without merging