Allow users with enterprise permissions to change notification settings
openfoodfoundation/openfoodnetwork pull request #7965
Opened 2021-07-22 17:54 UTC by andrewpbrett

#### What? Why?

Closes #7964 

#### What should we test?

A user with permissions for an enterprise should see editable fields on the Users tab of the enterprise

#### Release notes

Fixed a bug where users with permissions for an enterprise could not change notification settings

Changelog Category: User facing changes

#### Dependencies

#### Documentation updates

2021-07-22 19:39 UTC, andrewpbrett commented on spec/features/admin/enterprises_spec.rb
> +        select2_select enterprise_manager.email, from: 'receives_notifications_dropdown'
This is intended to test that there is a dropdown for the email address to receive notifications, but I'm not sure it's actually working as intended.

2021-07-22 23:43 UTC, mkllnk requested changes
Interesting, it seems like it has always been this way and suddenly it's an S2. :thinking: 

Anyway, it seems to be an important requirement. So let's do this. But the spec doesn't run. And when fixed up, I get an authorisation error. :disappointed:

2021-07-22 23:43 UTC, mkllnk commented on spec/features/admin/enterprises_spec.rb
> +    let(:enterprise) { create(:enterprise, users: [:enterprise_manager]) }
```suggestion
    let(:enterprise) { create(:enterprise, users: [enterprise_manager]) }
```

2021-07-22 23:43 UTC, mkllnk commented on spec/features/admin/enterprises_spec.rb
> +    end
```suggestion
    end

    it "allows me to edit notifications" do
      expect(page).to have_content enterprise.name

      accept_alert do
        within(".side_menu") { click_link "Users" }
      end

      select2_select enterprise_manager.email, from: 'receives_notifications_dropdown'
      expect(page).to have_no_selector '.select2-drop-mask' # Ensure select2 has finished
    end
```

2021-07-23 06:18 UTC, lin-d-hop commented
> Interesting, it seems like it has always been this way and suddenly it's an S2. 
> 
> Anyway, it seems to be an important requirement. So let's do this. But the spec doesn't run. And when fixed up, I get an authorisation error.

Yeah I'm also confused. But we had 2 of our oldest most experienced users get in touch saying it was broken.... Either they are both confused after the field disappeared last release, or somehow this was touched from somewhere else.

2021-07-23 08:45 UTC, RachL commented
I'm sorry I'm late to the party but are we sure we want to do this? 

Our user guide says: 

`Notifications: This is the email of the user to whom the OFN system correspondence will be directed, i.e. order confirmations etc. **Only the owner can nominate the user who will receive the notifications, among the enterprise managers list.** This user will have an envelope symbol next to their name in the managers' field.`

https://guide.openfoodnetwork.org/basic-features/enterprise-profile/enterprise-settings#users

I think it's kind of normal to not be able to have some feature reserved for the owner?

2021-07-29 16:49 UTC, andrewpbrett commented
I think we should close this PR and the corresponding issue. That screen is now functioning exactly as it was before the field was removed (which was definitely a mistake, we may want to think about how we could prevent things like that in the future). It's also functioning as it's described in the user guide. @lin-d-hop what do you think?

2021-07-29 17:08 UTC, lin-d-hop commented
Yeah agreed

2021-07-29 17:08 UTC, closed without merging