Update all stripe_connect eneterprise_id to stripe_sca
openfoodfoundation/openfoodnetwork pull request #8184
Opened 2021-09-14 09:32 UTC by apricot12

#### What? Why?

Closes #8169 

Migrates enterprise ID of Stripe Connect gateway to StripeSCA

#### What should we test?
- All StripeConnect payment methods updated to StripeSCA should have owner.

Changelog Category: Technical changes

2021-09-15 05:05 UTC, mkllnk requested changes
Nice!

I'm just wondering if we need to empty the cache.

@Matt-Yorkley How bad is it to call `Rails.cache.clear` in a migration? Or shall we do something more specific as in `Rails.cache.delete_matched("/spree/gateway/stripe_sca/enterprise_id/")`? Apparently, it can be slow iterating over all cache keys if the cache is big. But reconstructing the cache is slow, too. The other option is to query all payment methods from the database and delete those cache entries. Like here:

https://github.com/openfoodfoundation/openfoodnetwork/blob/2f5f2a03dd66b384e3c47c3b4d0df070c2134d35/db/migrate/20200912190210_update_weight_calculators.rb#L9

But I'm not sure if this is necessary. I guess that you can test that first by loading a wrongly migrated payment method in the UI as described in the issue, then running the migration and then reloading the page. Does it update?

2021-09-15 05:50 UTC, apricot12 commented
> Nice!
> 
> 
> 
> I'm just wondering if we need to empty the cache.
> 
> 
> 
> @Matt-Yorkley How bad is it to call `Rails.cache.clear` in a migration? Or shall we do something more specific as in `Rails.cache.delete_matched("/spree/gateway/stripe_sca/enterprise_id/")`? Apparently, it can be slow iterating over all cache keys if the cache is big. But reconstructing the cache is slow, too. The other option is to query all payment methods from the database and delete those cache entries. Like here:
> 
> 
> 
> https://github.com/openfoodfoundation/openfoodnetwork/blob/2f5f2a03dd66b384e3c47c3b4d0df070c2134d35/db/migrate/20200912190210_update_weight_calculators.rb#L9
> 
> 
> 
> But I'm not sure if this is necessary. I guess that you can test that first by loading a wrongly migrated payment method in the UI as described in the issue, then running the migration and then reloading the page. Does it update?

Yeah I wanted more feedback on deleting the rails cache. Thats why I went ahead and made this PR. I'm not really sure what would be the right thing to do. But I'll test it out as much as I can. 👍

2021-09-17 05:06 UTC, mkllnk requested changes
Sorry for the back and forth. I didn't know the whole context of this. I now think that your original version was the best! :smile:

2021-09-17 05:06 UTC, mkllnk commented on db/migrate/20210914084059_migrate_stripe_connect_enterprise_to_stripe_sca.rb
> +    Rails.cache.delete_if {|key, v| key =~ '/spree/gateway/stripe_connect/enterprise_id/' }
That's a great idea but I think that it only works with Redis. In my local environment I get an error:
```
NoMethodError: undefined method `delete_if' for #<ActiveSupport::Cache::FileStore:0x00005650efbe4d30>
```

But if this is deployed at the same time as the previous PR which introduces the issue, then we don't need to delete the cache.

Also, the above would need to iterate over all cache keys which is slow. Let's not do it unless we really have to.

2021-09-17 05:09 UTC, mkllnk approved these changes
I updated the commit to get this ready as soon as possible.

2021-09-17 08:47 UTC, filipefurtad0 commented
Hey @apricot12 and @mkllnk ,

To mimic de deployment process for the next release I've tried to make sure the staging server was on a similar state as current production servers, so I tested as following:

- staged v4.1.1 -> checked Stripe Connect was still available as an option on `/payment_methods`:

![image](https://user-images.githubusercontent.com/49817236/133752976-995fea7b-dbb4-4b55-b977-073dbb836406.png)

- deleted the previously ran migration:
![image](https://user-images.githubusercontent.com/49817236/133752799-ce68e574-ee83-4c8d-bd0f-a56ee59c458d.png)


- staged this PR which should run the migration again (currently in master) leave the Account Owner field not empty (this PR). Below we can see the page refreshing between deploys:

![Peek 2021-09-17 09-38](https://user-images.githubusercontent.com/49817236/133753122-ac7059e7-5758-495c-ae08-c01884a4d4b4.gif)

We can see that:

- `Stripe For Deletion` gets migrated to `Stripe SCA`
- Account owner `Red Berries` hub goes `empty` after staging; I would expect it to display the same account owner.

So I'm not sure this is working as expected. Do you agree with these testing steps? Let me know if you feel we should try something different. Added the `feedback` label.

2021-09-17 13:00 UTC, apricot12 commented
@filipefurtad0 There was a small syntax issue. Perhaps that could have caused the improper migration. It'd be best to test again.

2021-09-17 13:46 UTC, filipefurtad0 commented
I've had another look following the same procedure above, but deleted two migrations:

![image](https://user-images.githubusercontent.com/49817236/133791463-ebed4228-be44-4f4b-9ac9-427179243965.png)

Set-up the previous payment method and staged this PR, but got the same outcome...

After checking with @apricot12 , we've ran the following checks:

- checking if the **first migration** stripe Connect -> StripeSCA - `20210817100257` ran and worked:
![image](https://user-images.githubusercontent.com/49817236/133791583-d772bf93-74d6-4694-b033-683df16b27d1.png)

- checking if the **second migration** preferences migration - `20210914084059`  ran and worked:
![image](https://user-images.githubusercontent.com/49817236/133791398-96750bbe-cb03-49c5-8268-c795ee21b0d4.png)

Still no luck...

2021-09-17 13:56 UTC, filipefurtad0 commented
Moved to In Dev for now, as it might need a different approach as discussed with @apricot12 .

2021-09-19 22:38 UTC, mkllnk reviewed
I don't know what you two discussed but I need to prepare the release today. So I will revert the first PR which removed StripeConnect and we will need a new PR which migrates everything correctly.

2021-09-19 22:38 UTC, mkllnk commented on db/migrate/20210914084059_migrate_stripe_connect_enterprise_to_stripe_sca.rb
> +    execute "UPDATE spree_preferences SET key = replace( key, 'stripe_connect', 'stripe_sca') WHERE key LIKE '/spree/gateway/stripe_connect/'"
This won't work without the `%` at the end of the pattern.

2021-09-19 22:38 UTC, mkllnk commented on db/migrate/20210914084059_migrate_stripe_connect_enterprise_to_stripe_sca.rb
> +    execute "UPDATE spree_preferences SET key = replace( key, 'stripe_connect', 'stripe_sca') WHERE key LIKE '/spree/gateway/stripe_connect/'"
Testing locally, I found a duplicate key violation because the stripe_sca key already existed. But that may just be my development data.

2021-09-20 08:36 UTC, filipefurtad0 commented
Thanks @mkllnk ,

> So I will revert the first PR which removed StripeConnect and we will need a new PR which migrates everything correctly.

Seems like the best option until we are sure. As mentioned on the testing notes above: I could not get the preferences migrated in staging.

I've re-opened #7872 and grouped these in an Epic.

2021-10-06 15:25 UTC, closed without merging