Translate stripe error messages during payment processing
openfoodfoundation/openfoodnetwork pull request #8405
Opened 2021-10-25 15:31 UTC by jibees

#### What? Why?
Closes #7961
Stripe error messages aren't translated. 

But, Stripe send us an error code: use it (if found it _and_ translation key does exist) to translated the error message
Populate the en.yml file with some of the most known errors

#### What should we test?
Test that stripe error messages (with different card number: https://stripe.com/docs/testing#cards-responses): 
 - are well translated if the i18n key is present (ie. the errors are translated for the current langage)
 - use the default message coming from stripe if the i18n key is not present (ie. english)

#### Release notes
Add translation for Stripe errors

Changelog Category: User facing changes

2021-11-10 22:39 UTC, EmirVatric commented on app/models/spree/payment/processing.rb
> +        byebug
Hi, is this `byebug` a leftover?

2021-11-11 00:54 UTC, mkllnk requested changes

2021-11-11 00:54 UTC, mkllnk commented on app/models/spree/payment/processing.rb
> +        byebug
I can't see @EmirVatric's comment now but it's right, this needs to be removed.

2021-11-15 01:52 UTC, mkllnk approved these changes

2021-11-15 11:11 UTC, filipefurtad0 commented
Hey @jibees ,

To stage this PR it was proceeded as follows:

- staged the PR
- logged in to the server via ssh
- manually added the translations with `nano config/locales/fr_CA.yml `: To make this visible a label `FR...` was added to each string.
- re-started puma.service
- logged into the app as customer, selecting `fr_CA` locale.
- triggered some of the error messages added by this PR

As an example, here is the error message for `expired_card`, card 4000000000000069:
![image](https://user-images.githubusercontent.com/49817236/141771461-5c92011e-deb1-4dc1-b601-d4ea0133e208.png)

This works :tada: 

I've found there are still some cases which are not covered by the added keys, like `insufficient_funds`, card 4000008260003178 (3D-auth):

![image](https://user-images.githubusercontent.com/49817236/141771973-176c1bf0-eabf-4394-854b-ff7689ad77a0.png)

Or in the UI itself:
![image](https://user-images.githubusercontent.com/49817236/141772226-e490ac77-f265-432b-99b8-8f145eeca0c2.png)

But these can be addressed in separate issues :+1: 

Good to go.

2021-11-15 11:29 UTC, RachL commented
wow now I understand why users are unable to tell us what went wrong with their payments! If they see messages like for insufficient funds in English... 🤦

2021-11-15 13:25 UTC, jibees commented
Thanks @filipefurtad0 : feel free to open two separates issues for those two cases, they aren't the same I guess, but I'd be happy to tackle them ;)

2021-11-15 15:55 UTC, filipefurtad0 commented
Here they are @jibees #8489 and #8488.

2021-11-16 11:49 UTC, merged