7706 add close button to flatpickr
openfoodfoundation/openfoodnetwork pull request #8418
Opened 2021-10-27 09:25 UTC by KombiCode

#### What? Why?
Closes #7706

After discussions it was decided to add a 'Close' button which just closes the popover.
This should make things clearer for user on how to close

#### What should we test?

The new button has been added into datetimepicker and datepicker, so one need to test both.

As an admin go to eg Order Cycles, click on one datetime area to open the calendar, you should see a Close button on the right like illustrated in this screenshot :
<img width="356" alt="Capture d’écran 2021-10-27 à 11 16 22" src="https://user-images.githubusercontent.com/54935392/139037198-47611241-1244-40cd-ae6a-3bfe9a2fd973.png">
Clicking on it should close the popover
( A test has been added for this case in list_spec.rb in context 'using datetimepickers')

Similarly select Orders from the admin dashboard and click on eg Start date area, you should also see the Close button on the right like illustrated in this screenshot :
<img width="345" alt="Capture d’écran 2021-10-27 à 11 15 57" src="https://user-images.githubusercontent.com/54935392/139037600-8d28f8fc-b921-4071-a7df-e600f20306ef.png">
Clicking on it should close the popover
(A test has been added for this case in orders_spec.rb in context "with a complete order"

#### Release notes

Calendars now have a Close button to clearly indicate to the user a way to close the popover 

Changelog Category: User facing changes

2021-11-03 06:19 UTC, mkllnk requested changes
Great work!

I just added some suggestions to make it easier to read.

2021-11-03 06:19 UTC, mkllnk commented on spec/system/admin/order_cycles/list_spec.rb
> +          find(".shortcut-buttons-flatpickr-buttons > button:nth-last-child(1)").click
It's better to test for what the user sees:
```suggestion
          find("button", text: "CLOSE").click
```

2021-11-03 06:19 UTC, mkllnk commented on spec/support/features/datepicker_helper.rb
> +        find('.shortcut-buttons-flatpickr-buttons > button:nth-child(1)').click
Does this work?
```suggestion
        find("button", text: "TODAY").click
```

2021-11-03 06:19 UTC, mkllnk commented on spec/system/flatpickr_spec.rb
> +    it "opens the datepicker and sets date to today" do
We usually have empty lines in between examples.
```suggestion
    end

    it "opens the datepicker and sets date to today" do
```

2021-11-03 06:19 UTC, mkllnk commented on spec/system/flatpickr_spec.rb
> +  def open_datepicker(field)
```suggestion
  private

  def open_datepicker(field)
```

2021-11-03 08:47 UTC, KombiCode commented
> Great work!
> 
> I just added some suggestions to make it easier to read.

Thanks Maikel. I'm doing the requested changes and will push them asap.

2021-11-04 01:04 UTC, mkllnk approved these changes
:tada:

2021-11-04 12:47 UTC, filipefurtad0 commented
Hey @KombiCode ,

I think this is first contribution - welcome! :tada:

This looks great. I've checked several pages:

/admin/order_cycles/
/admin/order_cycles/[ORDER_ID]/edit
/admin/subscriptions/[subscription_id]/edit
/admin/orders/bulk_management
/admin/orders?q[s]=completed_at+desc#


and reports:

Orders And Distributors
Bulk Co-Op
Payment Reports
Orders & Fulfillment Reports
Enterprise Fee Summary
Order Cycle Management
Sales Tax
Xero Invoices
Packing Reports

Posting only these two as examples:

**Orders page - date-picker**
![image](https://user-images.githubusercontent.com/49817236/140314519-84aa5bf2-c21e-4083-9edb-684bade03f0c.png)

**Order Cycles - date-time-picker**
![image](https://user-images.githubusercontent.com/49817236/140314530-880a6e61-52a1-4f6b-88c8-3a9888e4ba7a.png)

This introduces no changes on mobile - this is expected:

Android 12, Chrome
![image](https://user-images.githubusercontent.com/49817236/140314488-6549194d-2c86-44e3-bbf7-eeaac21ee2eb.png)

Android 12, Firefox 
![image](https://user-images.githubusercontent.com/49817236/140314507-8dc4ba60-b0cc-4ed4-bef0-582dff40ce24.png)

iPhone / Safari
![image](https://user-images.githubusercontent.com/49817236/140314494-20ec4e67-fe0b-4989-9128-af6b4067bb26.png)


**Summary**

We now see the `Close` button now appears; it behaves similarly as to clicking away from the calendar area, before or after editing dates. 

Awesome work - thanks for adding the tests too :tada: 
Good to go.

2021-11-04 15:06 UTC, KombiCode commented
> Hey @KombiCode ,
> 
> I think this is first contribution - welcome! 🎉
> 
> This looks great. I've checked several pages:
> 
> /admin/order_cycles/ /admin/order_cycles/[ORDER_ID]/edit /admin/subscriptions/[subscription_id]/edit /admin/orders/bulk_management /admin/orders?q[s]=completed_at+desc#
> 
> and reports:
> 
> Orders And Distributors Bulk Co-Op Payment Reports Orders & Fulfillment Reports Enterprise Fee Summary Order Cycle Management Sales Tax Xero Invoices Packing Reports
> 
> Posting only these two as examples:
> 
> **Orders page - date-picker** ![image](https://user-images.githubusercontent.com/49817236/140314519-84aa5bf2-c21e-4083-9edb-684bade03f0c.png)
> 
> **Order Cycles - date-time-picker** ![image](https://user-images.githubusercontent.com/49817236/140314530-880a6e61-52a1-4f6b-88c8-3a9888e4ba7a.png)
> 
> This introduces no changes on mobile - this is expected:
> 
> Android 12, Chrome ![image](https://user-images.githubusercontent.com/49817236/140314488-6549194d-2c86-44e3-bbf7-eeaac21ee2eb.png)
> 
> Android 12, Firefox ![image](https://user-images.githubusercontent.com/49817236/140314507-8dc4ba60-b0cc-4ed4-bef0-582dff40ce24.png)
> 
> iPhone / Safari ![image](https://user-images.githubusercontent.com/49817236/140314494-20ec4e67-fe0b-4989-9128-af6b4067bb26.png)
> 
> **Summary**
> 
> We now see the `Close` button now appears; it behaves similarly as to clicking away from the calendar area, before or after editing dates, as mentioned [here](https://github.com/openfoodfoundation/openfoodnetwork/issues/7706#issuecomment-951704505).
> 
> Awesome work - thanks for adding the tests too 🎉 Good to go.

Hi @filipefurtad0,

Thanks for your comments and checks.
Indeed this is my first contribution 😅, will start another one soon.

2021-11-05 00:04 UTC, merged