If an order has out of stock line items display them and let admins remove them
openfoodfoundation/openfoodnetwork pull request #8438
Opened 2021-10-29 18:56 UTC by cillian

#### What? Why?

For #8178. Before only customers could delete out of stock line items and out of stock line items would not be displayed when an order was viewed in the admin area. This changes things so the out of stock line items are displayed in the admin area and gives the admin the ability to delete them.

#### What should we test?

1. First follow the _Steps to reproduce_ in the issue #8178.
2. Then make sure the out of stock line item is visible on the edit order page in the admin area.
3. Then make sure you can delete the out of stock line item.

#### Release notes

If an order has out of stock line items display them and let admins remove them.

Changelog Category: User facing changes

![insufficient-stock-lines](https://user-images.githubusercontent.com/101088/139487654-5d33b853-2d9b-4a9a-9307-b0653731e723.gif)

2021-11-03 07:19 UTC, mkllnk approved these changes
Nice!

Can you resolve the merge conflict?

2021-11-03 19:45 UTC, cillian commented
@mkllnk no problem. I _think_ this is okay now, I rebased with the latest `master` but didn't get a conflict.

2021-11-16 15:05 UTC, Matt-Yorkley requested changes
Alright... so as a bit of background to the underlying issue; the cart page has a certain bit of logic that uses line items with zero quantity as a kind of "placeholder" to allow the customer to see when an item in their cart has gone out of stock whilst shopping. You can't tell the customer which item is out of stock unless you keep a record in the database of that item. Makes sense. The problem with that is that the _rest_ of the app code is not designed with that implementation in mind; the idea that a line item with zero quantity can even exist is basically a total anomaly from the point of view of the backoffice code, for example. That's where this inconsistency comes from, there's certain cases where these zero-quantity items can be created but the order edit page doesn't recognise them.

I think the approach you've gone for is good, it's definitely moving things in the right direction. There's a little bit more complexity here that needs looking at though.

So... these zero-quantity items should only really exist in orders in an incomplete state, and they should only really be temporary. When a line item is in the cart but the order is not completed, the item hasn't actually been _sold_ yet and the stock has not been reduced. An order can't be completed with a zero-quantity line item (because they can't be sold). Also; _after_ an order is completed the items actually are sold, and the stock is reduced. At this point the sale has been done, and for example one of those line items in the order could very well be pointing to a product which _has_ subsequently gone out of stock (imagine an order is placed for the last bag of carrots, after the order is completed there are no carrots left).

If you edit a _completed_ order (with this PR) and some of the items are out of stock, it will show the "out of stock" feedback in big red letters, which is not actually correct in that context. So I think what we need to do is only apply that check (`if @order.insufficient_stock_lines.any?`) and the show the "out of stock" items when the order is not yet complete. 

Does that make sense?

Whew, I had to burn a few neurons there putting all that into words :sweat_smile:

2021-11-16 15:13 UTC, Matt-Yorkley commented on app/views/spree/admin/orders/_form.html.haml
> +  - if @order.insufficient_stock_lines.any?
TLDR version:
```suggestion
  - if !@order.completed? && @order.insufficient_stock_lines.any?
```
I think that'll be enough :point_up: 

We might want a little bit more in terms of test coverage though.

2021-12-03 13:13 UTC, cillian commented
@Matt-Yorkley Thanks for the detailed explanation :sweat_smile:, good to know. I have made that adjustment now, added view specs and rebased.

2022-01-07 13:18 UTC, Matt-Yorkley approved these changes
Thanks :heart:

2022-01-07 13:20 UTC, Matt-Yorkley commented
Note: I rebased on master and tweaked some of the CSS bits, as we've recently changed how our CSS assets are bundled :ok_hand:

2022-01-24 12:17 UTC, filipefurtad0 commented
Hey @cillian ,
Thanks for this improvement!

Before this PR:

![image](https://user-images.githubusercontent.com/49817236/150779283-8b5e3200-d2a0-4429-8e1f-9663c4946915.png)

After this PR:
There is agreement with the order information displayed for the shopfront (customer) and backoffice (admin). Now the admin can:

- delete any line items out of stock
- add other items to the order -> this 'unblocks' the order and allows the customer to finish checking out or allows order complettion in the babkoffice.

Awesome!! :tada: 
Good to go.

2022-01-24 12:18 UTC, merged