Update code for active storage and rake task
openfoodfoundation/openfoodnetwork pull request #8470
Opened 2021-11-10 08:14 UTC by mkpdev

1.  Update Config to use ActiveStorage
   2. Update Models, Views, and Controllers
   3.  Migrate Attachment Files
   4.  Code Cleanup

Closes #[the issue number this PR is related to]

#### What should we test?

#### Release notes

Changelog Category: User facing changes | Technical changes

#### Dependencies

#### Documentation updates

2021-11-17 02:40 UTC, mkllnk commented
Hi @mkpdev!

Thank you for picking this up. It's not an easy task. :muscle: 

I'm a bit confused about your two PRs though. They are missing a good description beyond your dotpoints. For example, your second PR seems to include the first one but you didn't explain why. Should they be deployed separately?

You didn't include a reference to the issue, release notes or testing instructions. These are all necessary to progress with this pull request.

And several specs are failing. Are you able to fill in the gaps and make this a complete and working contribution?

2021-11-19 06:26 UTC, mkpdev commented
> Hi @mkpdev!
> 
> Thank you for picking this up. It's not an easy task. muscle
> 
> I'm a bit confused about your two PRs though. They are missing a good description beyond your dotpoints. For example, your second PR seems to include the first one but you didn't explain why. Should they be deployed separately?
> 
> You didn't include a reference to the issue, release notes or testing instructions. These are all necessary to progress with this pull request.
> 
> And several specs are failing. Are you able to fill in the gaps and make this a complete and working contribution?

@mkllnk Both PRs, comments are updated please have a look. Thanks

2021-11-23 06:55 UTC, mkllnk requested changes
Thank you for updating the pull request description. That's very helpful.

There is still some information missing:

- Link to issue.
- Link to related PR.
- Downtime considerations. How long does the rake task run for? What do we do with images that were uploaded in the meantime?
- Testing instructions.
- Release notes.

> The actual attachments will be copied to the ActiveStorage directory structure.

That sounds slow and unnecessary. I thought that one of the cool features of ActiveStorage is that you can define any key. So instead of generating a random key, can't we supply the path to the existing image file?

Did you have a look at the failing specs as well? We currently have one spec failing in master that is unrelated to your pull request but you have a lot more failing. Your pull request breaks something.

2021-11-23 06:55 UTC, mkllnk commented on app/models/spree/image.rb
> +      url_for(attachment.variant(resize: "48x48#"))
I think that we should define this size in one place. Maybe we can add methods to the Spree::Image class that call `attachment.variant` with our standardised sizes?

2022-05-31 00:47 UTC, closed without merging