Display remaining stock in shopfront if enabled in shop preferences
openfoodfoundation/openfoodnetwork pull request #8841
Opened 2022-02-07 09:04 UTC by apricot12

#### What? Why?

Closes #8790 

This improves the customer experience by enabling them to know that the product is in limited stock and must be ordered ASAP if required.

#### What should we test?
- Visit `#admin/products` page.
- Ensure at least one product in an order cycle has <= 3 units left.
- Go to the shopfront with the aforementioned product.
- Ensure that stock left is displayed under the `Add` button in `#E54E47` colour.

#### Release notes

Changelog Category: User facing changes 

The title of the pull request will be included in the release notes.

2022-03-15 06:30 UTC, RachL commented
hello @apricot12 don't forget to push this one forward ;)

2022-03-29 13:19 UTC, jibees commented
Hey @apricot12 !
There you go: please, find on your branch my two commits for this PR.
I'd be happy if you could implements the specs.
I think the commits says it all, and here are the screenshots:
<img width="470" alt="Capture d’écran 2022-03-29 à 14 57 08" src="https://user-images.githubusercontent.com/296452/160620373-8ebaed01-1112-4c52-ab05-59270279558d.png">
<img width="704" alt="Capture d’écran 2022-03-29 à 14 56 38" src="https://user-images.githubusercontent.com/296452/160620388-a895eaa8-1447-4e29-aed3-16abae866ce6.png">

2022-03-29 13:25 UTC, apricot12 commented
> Hey @apricot12 !
> 
> There you go: please, find on your branch my two commits for this PR.
> 
> I'd be happy if you could implements the specs.
> 
> I think the commits says it all, and here are the screenshots:
> 
> <img width="470" alt="Capture d’écran 2022-03-29 à 14 57 08" src="https://user-images.githubusercontent.com/296452/160620373-8ebaed01-1112-4c52-ab05-59270279558d.png">
> 
> <img width="704" alt="Capture d’écran 2022-03-29 à 14 56 38" src="https://user-images.githubusercontent.com/296452/160620388-a895eaa8-1447-4e29-aed3-16abae866ce6.png">
> 
> 
> 
> 

This is great! Thanks. I'll write the specs 👍

2022-04-12 01:19 UTC, mkllnk requested changes
Nice! I think that we should improve the naming though, just in case we want to add another similar option in the future.

2022-04-12 01:19 UTC, mkllnk commented on app/models/enterprise.rb
> +  preference :product_stock_display, :boolean, default: false
Maybe `:shopfront_low_stock_display` would be more accurate? We are not displaying stock all the time.

2022-04-12 01:19 UTC, mkllnk commented on config/locales/en.yml
> +          display_remaining_stock_tip: "Display remaining stock in shopfront"
This is not entirely true. We do that only if stock is low.

2022-04-12 01:19 UTC, mkllnk commented on config/locales/en.yml
> +          display_remaining_stock_tip: "Display remaining stock in shopfront"
Why do we need a tooltip if it's not showing us any more information? Maybe we should explain a bit more here.

2022-04-12 01:19 UTC, mkllnk commented on config/locales/en.yml
> +          display_remaining_stock_tip: "Display remaining stock in shopfront"
```suggestion
          display_remaining_stock: "Display low stock in shopfront"
          display_remaining_stock_tip: "Let shoppers know when there are only 3 or less items left."
```

2022-04-12 23:57 UTC, mkllnk approved these changes
Thank you!

2022-04-13 07:48 UTC, jibees approved these changes
> This branch has conflicts that must be resolved

I'd be happy if some of commit would be squashed to clean git history, but it may be impossible/time consuming.

2022-04-13 07:51 UTC, apricot12 commented
> > This branch has conflicts that must be resolved
> 
> 
> 
> Needs to be resolved 😮‍💨 
> 
> 
> 
> I'd be happy if some of commit would be squashed to clean git history, but it may be impossible/time consuming.
> 
> 

I'll resolve it. Just wanted you to have a final look 😁. I'll also see if I can squash some commits together, at least a couple of them I think can be squashed.

2022-04-14 12:33 UTC, jibees commented
Don't know if (or I guess) it's supposed to be fixed, but there's still some conflicting files @apricot12 . 
Sorry if it's redundant ;)

2022-04-14 12:35 UTC, apricot12 commented
> Don't know if (or I guess) it's supposed to be fixed, but there's still some conflicting files @apricot12 . 
> 
> Sorry if it's redundant ;)

I've tried rebasing this one a few times and I'm frustrated. So what happens is that when i rebase against master to fix the conflict, it dumps all the commits from master into this branch, polluting the PR. I'm thinking about creating an orphan branch from this and cherry-picking at this point.

2022-04-15 01:01 UTC, mkllnk commented
Let's see if I can resolve this. I'll just dump everything I do here for transparency. First a look at the history of this branch:
```
* 15ac3c27f - (3 days ago) Update i18n to be more informative - Nihal Mohammed (HEAD -> 8790_display_stock_left_shop)
* ff20be2be - (3 days ago) Rename product_stock_display to product_low_stock_display - Nihal Mohammed
* 6a4e4df8b - (3 days ago) Add system spec - Nihal Mohammed
* 065f6e35e - (2 weeks ago) i18n for shop preferences in admin - Jean-Baptiste Bellet
* 8c0ab7aa5 - (2 weeks ago) Add mocked shopfront - Jean-Baptiste Bellet
* 66414de19 - (2 weeks ago) Display remaining stock for variant in the shopfront - Jean-Baptiste Bellet
* 0102bc003 - (2 weeks ago) i18n for shop preferences - Jean-Baptiste Bellet
* 593cdb5c8 - (2 months ago) Add Display stock option to enterprises form - Nihal M. Kelanthodika
* 0d7a04357 - (2 months ago) Add preferred_product_stock_display to Enterprise model, serializer and permitted attributes. (Fixed alignment of guest orders radio button as well) - Nihal M. Kelanthodika
*   9a8082e35 - (6 weeks ago) Merge pull request #8947 from openfoodfoundation/dependabot/npm_and_yarn/karma-6.3.17 - Maikel
```

That looks straight forward, linear commits on 6 weeks old master. Let's try a rebase:
```
git fetch upstream master:master
git rebase master
...
error: Failed to merge in the changes.
Patch failed at 0001 Add preferred_product_stock_display to Enterprise model, serializer and permitted attributes. (Fixed alignment of guest orders radio button as well)
hint: Use 'git am --show-current-patch' to see the failed patch
```

Three files with a conflict. I'm looking at the current patch to see the intent and resolve it. A new preference has been added in master and in this branch. I just need to add both preferences to resolve. But, hang on, the first commit adds a lot more attributes to the EnterpriseSerializer, duplicating some of the existing one. I think that a previous rebase has gong wrong and the conflict wasn't resolved correctly:

```
      attributes :name, :id, :is_primary_producer, :is_distributor, :sells, :category, :permalink,
                 :payment_method_ids, :shipping_method_ids, :producer_profile_only,
                 :long_description, :preferred_product_selection_from_inventory_only,
                 :preferred_shopfront_message, :preferred_shopfront_closed_message,
                 :preferred_shopfront_taxon_order, :preferred_shopfront_producer_order,
                 :preferred_shopfront_order_cycle_order, :show_customer_names_to_suppliers,
                 :preferred_shopfront_product_sorting_method, :owner, :contact, :users, :tag_groups,
                 :default_tag_group, :require_login, :allow_guest_orders, :allow_order_changes,
                 :logo, :promo_image, :terms_and_conditions,
                 :terms_and_conditions_file_name, :terms_and_conditions_updated_at,
<<<<<<< HEAD
                 :preferred_invoice_order_by_supplier
=======
                 :preferred_shopfront_order_cycle_order, :preferred_product_stock_display,
                 :show_customer_names_to_suppliers, :preferred_shopfront_product_sorting_method,
                 :owner, :contact, :users, :tag_groups, :default_tag_group, :require_login,
                 :allow_guest_orders, :allow_order_changes, :logo, :promo_image, :terms_and_conditions,
                 :terms_and_conditions_file_name, :terms_and_conditions_updated_at
>>>>>>> Add preferred_product_stock_display to Enterprise model, serializer and permitted attributes. (Fixed alignment of guest orders radio button as well)
```

Okay, I can resolve that and continue. It stops again:
```
CONFLICT (content): Merge conflict in app/serializers/api/admin/enterprise_serializer.rb
Recorded preimage for 'app/serializers/api/admin/enterprise_serializer.rb'
error: Failed to merge in the changes.
Patch failed at 0007 Add system spec
```

That's the file I had to modify for the conflict resolution. The commit was just fixing linting errors though. My previous resolution didn't add any linting errors to fix. So this file doesn't need any modification in this commit. Continue:

```
Patch failed at 0008 Rename product_stock_display to product_low_stock_display
```

The attributes were just formatted in a different way and Git couldn't recognise that. Easy to resolve. Continue and finished. Let's push and see what Github does. ... 9 commits, that's correct. Maybe you were rebasing on the wrong master branch?

2022-04-15 07:21 UTC, jibees approved these changes
Thanks!

2022-04-15 16:58 UTC, filipefurtad0 commented
Hey @apricot12 ,

Thanks for this improvement. Looking at the acceptance criteria and your what to test section:

- with the introduced option disabled

![Peek 2022-04-15 17-39](https://user-images.githubusercontent.com/49817236/163597577-501c5b98-44e7-4017-bd45-0ee0b6579f37.gif)

- with the introduced option enabled

![Peek 2022-04-15 17-40](https://user-images.githubusercontent.com/49817236/163597616-87fd3d7f-66d2-4aa6-974c-11361a0140bf.gif)

**Summary**
- The option is disabled by default
- Radio button alignment is fixed (before, left; after, right):

![image](https://user-images.githubusercontent.com/49817236/163598476-17c9bbb4-d7b3-4bd3-a07c-74edb01b234b.png)

With the feature activated:
- on demand variant aren't displaying any message (current behavior)
- all variant with on_hand value being 3 or less are showing the correct (introduced) message. It disappears once an item is added into the cart.

**Note**: this PR does not introduce any change in items which can be added in bulk. 

This looks great, merging :+1: 

PS: I think it would have been useful to have a system test on `spec/system/admin/enterprises_spec.rb` which asserts that
i) the new stock option can be found/seen under the Shop Preferences tab, and
ii) that choosing the Enable/Disable radio buttons correctly sets `:product_stock_display` to `true` or `false`, respectively
What do you think?

2022-04-15 16:58 UTC, merged