Delete linked coordinators_fees when deleting an OrderCycle
openfoodfoundation/openfoodnetwork pull request #8950
Opened 2022-03-02 10:08 UTC by jibees

#### What? Why?
There was a `InvalidForeignKey` when deleting a cloned OrderCycle, due to existing `coordinators_fees`. This PR adds a `dependent: :destroy` on `coordinator_fees` for an `order_cycle`

Closes #5903

#### What should we test?

 - Clone an order cycle (with coordinator fees)
 - Delete the new created order cycle
 - This should be possible without any error

#### Release notes

Changelog Category: User facing changes

The title of the pull request will be included in the release notes.

2022-03-03 00:47 UTC, mkllnk approved these changes
Spec?

2022-03-03 08:10 UTC, jibees commented
> Spec?

Done: [5fc7d72](https://github.com/openfoodfoundation/openfoodnetwork/pull/8950/commits/5fc7d72b09b9bc508bf31e9b587b5029b8f1fe49)

I'm a bit afraid with this one: actually I thought that some tests will failed, but none failed. Deleting associated coordinator_fees when deleting OC seems to be ok (at least in term of spec). I'm still wondering if it's ok in term of user/product point of view...

2022-03-04 03:37 UTC, mkllnk requested changes
Thank you for your reflection on this! It made me look into the data model and an enterprise fee `has_many :order_cycles`. So we can't just delete it. I think that we need to do something like an around_destroy action that:

- checks for coordinator fees
- disassociates those fees
- [destroy oc]
- check if the fees are associated to anything else or now orphans
- destroy orphaned fees

2022-03-04 03:37 UTC, mkllnk commented on spec/controllers/admin/order_cycles_controller_spec.rb
> +      describe "when an order cycle has any coordinator_fees", :debug do
```suggestion
      describe "when an order cycle has any coordinator_fees" do
```

2022-03-04 03:39 UTC, mkllnk commented
With your testing steps and your current implementation, is the fee deleted from the original OC or is it duplicated for the cloned OC?

If it's deleted (which would be a bug) then it could be good to write that down as a spec for cloning OCs as well.

2022-03-04 08:32 UTC, jibees commented on spec/controllers/admin/order_cycles_controller_spec.rb
> +      describe "when an order cycle has any coordinator_fees", :debug do
🤦

2022-03-04 10:15 UTC, jibees commented
Ok, this post is here to try to understand, and 

###### Dataset
`OC_2`, the original
`OC_9`, the cloned from `OC_2`

Retrieving `coordinator_fees` for `OC_2`: 
```
select * from coordinator_fees where coordinator_fees.order_cycle_id = 2;

id | order_cycle_id | enterprise_fee_id
-- | -- | --
2 | 2 | 4
```

Retrieving `coordinator_fees` for `OC_9`: 
```
select * from coordinator_fees where coordinator_fees.order_cycle_id = 9;


id | order_cycle_id | enterprise_fee_id
-- | -- | --
9 | 9 | 4
```

###### Conclusions I've made
The `coordinator_fees` data is copied when an OC is cloned. A `coordinator_fees` is only linked with one order_cycle. It reference then an `enterprise_fee` which is the same (in the previous sql query, you could see that `enterprise_fee_id` is `4` for both `coordinator_fee`).

For all those reasons, I thought could be a good idea to delete the associated `coordinator_fees` when deleting an order cycle.

###### To answer your questions
> With your testing steps and your current implementation, is the fee deleted from the original OC or is it duplicated for the cloned OC?

I didn't test with a cloned OC (which I probably should), but when deleting an OC, it deletes the `coordinator_fees` that is associated to its OC (in our exemple, if we delete the `OC_9`, the `coordinator_fees` with id `9` will by deleted)

2022-03-04 10:35 UTC, jibees commented
I've pushed one commit that #[7ca6434](https://github.com/openfoodfoundation/openfoodnetwork/pull/8950/commits/7ca6434b1410b9b2eb831a4592dd96131b996f59) should actually improve the test coverage. 
Will be happy if you can check it out.

2022-03-06 22:24 UTC, mkllnk approved these changes
Great, thank you!

That was thorough investigating. :slightly_smiling_face: 

I didn't realise the difference between coordinator fees and exchange fees. Both associate an enterprise fee with an order cycle but exchange fees are associated via the participating enterprises while the coordinator fee can be associated directly because the coordinator doesn't need to be one of the trading enterprises.

Your new spec is excellent!

2022-04-14 08:43 UTC, jibees commented
This one is more than 1 month old, has been reviewed by @mkllnk --> moving to `Test Ready` column.
If you feel that this should not happened, feel free to move it back to `Code Review` column.

2022-04-18 10:55 UTC, filipefurtad0 commented
Hey @jibees ,

Many thanks for the detailed investigation and discussion! 

> I didn't realise the difference between coordinator fees and exchange fees. 

I also had forgotten all about them @mkllnk :-) There's really plenty of granularity as of where to place the fee in the OC :sweat_smile: 

So, after reproducing the error (cloned OC + coordinator fee), the PR was staged and it was verified that:

- the cloned OC can now be deleted - no error message :+1: 
- the coordinator fee is not deleted from the OC from it was cloned - it can be seen below:

![Peek 2022-04-18 11-46](https://user-images.githubusercontent.com/49817236/163797953-dad602c8-42b1-4dac-9a84-81f88b8aecd9.gif)

Before deleting:

```
openfoodnetwork=> select * from coordinator_fees where coordinator_fees.order_cycle_id = 3585;
 order_cycle_id | enterprise_fee_id | id  
----------------+-------------------+-----
           3585 |               299 | 468
(1 row)

openfoodnetwork=> select * from coordinator_fees where coordinator_fees.order_cycle_id = 3586;
 order_cycle_id | enterprise_fee_id | id  
----------------+-------------------+-----
           3586 |               299 | 469
(1 row)
```

After deleting:

```

openfoodnetwork=> select * from coordinator_fees where coordinator_fees.order_cycle_id = 3586;
 order_cycle_id | enterprise_fee_id | id 
----------------+-------------------+----
(0 rows)

openfoodnetwork=> select * from coordinator_fees where coordinator_fees.order_cycle_id = 3585;
 order_cycle_id | enterprise_fee_id | id  
----------------+-------------------+-----
           3585 |               299 | 468
```

Good to go, merging - thanks :tada:

2022-04-18 10:55 UTC, merged