Handle `items` in bulk order management
openfoodfoundation/openfoodnetwork pull request #9132
Opened 2022-04-26 13:39 UTC by jibees

#### What? Why?

Closes #8540

#### What should we test?

- Create product that is set to `items` quantity (_sachets_ means bags, pouch in french) and is available for bulk mode
<img width="563" alt="Capture d’écran 2022-04-25 à 16 11 44" src="https://user-images.githubusercontent.com/296452/165311148-30e077ce-18a7-4d08-9ba2-a8e95d80dc01.png">

- Set a Group By value
<img width="537" alt="Capture d’écran 2022-04-26 à 15 32 06" src="https://user-images.githubusercontent.com/296452/165311450-c27b34b4-aaf3-419c-a526-721074cc6f69.png">

- Checkout that product, and see the Bulk Order Management interface
<img width="1446" alt="Capture d’écran 2022-04-26 à 15 33 13" src="https://user-images.githubusercontent.com/296452/165312694-d8f3fdfa-24b9-43b9-b033-1a39e3526e73.png">

It should not affect the interface in metric and imperial system, but I'd think it worth a check (before and after the PR) ; see previous PR maybe for help (https://github.com/openfoodfoundation/openfoodnetwork/pull/8565)

#### Release notes

Changelog Category: User facing changes

The title of the pull request will be included in the release notes.

#### Dependencies

#### Documentation updates

2022-04-27 02:27 UTC, mkllnk requested changes
Looks good to me, except one line. :wink:

2022-04-27 02:27 UTC, mkllnk commented on spec/javascripts/unit/admin/line_items/controllers/line_items_controller_spec.js.coffee
> +        fit "returns the sum of the product of unit_value and maxOf(max_quantity, pristine quantity) for specified line_items", ->
```suggestion
        it "returns the sum of the product of unit_value and maxOf(max_quantity, pristine quantity) for specified line_items", ->
```

2022-04-27 09:22 UTC, jibees commented
> Looks good to me, except one line. 😉

Thanks for your attention @mkllnk ... (maybe I should configure a pre-commit hook ;))

2022-04-27 23:14 UTC, mkllnk approved these changes

2022-05-09 05:40 UTC, mkllnk reviewed
Moving to test ready.

2022-05-29 15:18 UTC, drummer83 commented
@RachL: You are still assigned to this issue. Would you like to test it or can someone else pick it up?

2022-05-30 07:38 UTC, RachL commented
@drummer83 go ahead :)

2022-06-09 19:11 UTC, drummer83 commented
Thanks @jibees for this PR. Finally I was able to test it.

I set up products with items as unit and also metric and imperial units and activated Group Buy for them.
Then I went shopping with three different customers and checked the BOM page.
Here are my results:

**Before this PR:**
The BOM page didn't show the ordered quantities for 'items':
![grafik](https://user-images.githubusercontent.com/1790176/172925156-1044bbaa-68ed-45da-a3ef-caf1a826e116.png)

**After this PR:**
Items are now nicely displayed on BOM page. The calculations are correct. Cool! :sunglasses: 
![grafik](https://user-images.githubusercontent.com/1790176/172923594-c32a1f6e-b270-4609-92e3-01bf2ae49fb7.png)

As requested I have also tested imperial units, which is also looking good:
![grafik](https://user-images.githubusercontent.com/1790176/172923716-951d259d-6dab-4f60-a18e-ac160955697d.png)

I think this one is ready to go! :champagne:

2022-06-10 08:08 UTC, merged

2022-06-14 16:20 UTC, RachL commented
@jibees I'm noticing "items" is not translated. Can we use a key or better display the unit name (like "botte" "panier") ?

![image](https://user-images.githubusercontent.com/6525576/173626966-70095109-e9ce-4218-81d0-883c2390d1f7.png)

2022-06-15 06:28 UTC, jibees commented
@RachL 
It's not that easy unfortunately. I noticed that and I forgot to open an issue.