8698-fix-shipped-email-tracking-information-font-size
openfoodfoundation/openfoodnetwork pull request #9237
Opened 2022-05-27 22:50 UTC by mgrigoriev8109

#### What? Why?

Closes #8698 

The tracking information in a shipped email looked different from the rest of the email body, and is now updated to be identical by increasing the font size to 17, since it's already the same font family. 

#### What should we test?
The email styling can be tested manually by visiting http://localhost:3000/rails/mailers/spree/shipment/shipped on a local machine running the server. 

It will not display the tracking information, as the normal shipped email does not contain any - but if you go into `app/views/spree/shipment_mailer/shipped_email.html.haml` and add `- @shipment.tracking = "test tracking information"` on line 16, turning it into 
```
- @shipment.tracking = "test tracking information"
- if @shipment.tracking
  %p{ style: "font-size: 17px;" }
    = t('.track_information', tracking: @shipment.tracking)
```
, then you can see the change occur when you refresh the page. 

My understanding is that the shipped email currently has far too many different fonts, and the aim is to decrease the total amount. 

#### Release notes

Changelog Category: User facing changes

2022-05-30 08:04 UTC, jibees approved these changes
Thanks for your contribution 👌 

The testing notes probably needs to be updated as we can't change the code at the testing time, but I'm sure testers team will find a way to test it ;)

You should update your PR's title as well, as it is used in the release notes.

2022-05-31 06:30 UTC, mkllnk requested changes
Good start but I have a suggestion below. I'll also push another commit which will make the testing easier. Testing an email actually sent from a staging server would also be good in the testing instructions.

2022-05-31 06:30 UTC, mkllnk commented on app/views/spree/shipment_mailer/shipped_email.html.haml
> +  %p{ style: "font-size: 17px;" }
I think that it would be more consistent to use `p.lead` here so that the formatting is the same as other paragraphs, too.

2022-06-01 06:11 UTC, jibees approved these changes
This set of commits is very clear. 💪

2022-06-01 06:19 UTC, mkllnk approved these changes
That looks great, thank you.

2022-06-02 17:26 UTC, filipefurtad0 commented
Hi @mgrigoriev8109 , welcome :tada: 

I've added some random tracking info on two orders, and generated the shipment email, before (left) and after (right) staging the PR. Results are below:

![image](https://user-images.githubusercontent.com/49817236/171688439-7eebcac9-36ae-423a-9596-c66b99a8a0d8.png)

Thanks for improving this!
Good to go, merging.

2022-06-02 17:37 UTC, merged