Add boolean to specify if enterprise abn number is mandatory or not to generate invoices
openfoodfoundation/openfoodnetwork pull request #9348
Opened 2022-06-23 14:43 UTC by jibees

#### What? Why?

Closes #9315

#### What should we test?
 - Visit `/admin/invoice_settings/edit`
 - `REQUIRE AN ABN NUMBER TO GENERATE AN INVOICE?` should be checked
<img width="331" alt="Capture d’écran 2022-06-23 à 16 39 38" src="https://user-images.githubusercontent.com/296452/175326180-fd408a42-7ca2-4c08-b8f1-01b4cfa72c74.png">
 - For an enterprise without any ABN number,
<img width="920" alt="Capture d’écran 2022-06-23 à 16 39 55" src="https://user-images.githubusercontent.com/296452/175326320-9baec3e7-cc67-47d4-94c6-69c9bcd32076.png">
 - ... it must be impossible to print/send invoice (blocked with a js alert): 
<img width="493" alt="Capture d’écran 2022-06-23 à 16 41 42" src="https://user-images.githubusercontent.com/296452/175326578-2a773ae8-5dc0-4d51-ac47-50c33f15976f.png">
 
- then, add a ABN number
- you should be able to generate (print/send) invoice

 - then, remove ABN number
 - uncheck `REQUIRE AN ABN NUMBER TO GENERATE AN INVOICE?` under `/admin/invoice_settings/edit`
 - you should be able to generate (print/send) invoice

#### Release notes

Changelog Category: User facing changes | Technical changes

The title of the pull request will be included in the release notes.

#### Dependencies

#### Documentation updates

2022-06-28 03:02 UTC, mkllnk requested changes
Nice!

I have only style requests... :smile:

2022-06-28 03:02 UTC, mkllnk commented on app/helpers/spree/admin/orders_helper.rb
> +      def print_invoice_link_without_url
```suggestion
      def notify_about_required_abn
```

2022-06-28 06:47 UTC, jibees commented on app/controllers/admin/invoice_settings_controller.rb
> +        :enable_mandatory_abn_number?,
Therefor, I'm wondering if we should use ABN or something else?
As I can see that it's translated to `NIF` (ca), `GST No.` (nz), `Company Number` (en), `SIRET` (fr), ...

Why not use _company number_? I think it's the most generic we have

2022-06-28 07:20 UTC, mkllnk commented on app/controllers/admin/invoice_settings_controller.rb
> +        :enable_mandatory_abn_number?,
In OFN, we use the term *enterprise*. So we could call it Enterprise Number.

2022-06-29 00:28 UTC, mkllnk approved these changes
That reads much better now. :smile:

2022-06-29 18:07 UTC, filipefurtad0 commented
Agree! Merging :+1:

2022-06-29 18:07 UTC, merged

2022-07-04 11:34 UTC, filipefurtad0 commented
Hey @jibees,

While testing, it seems I've missed these lines from your detailed testing steps:

> then, remove ABN number

> uncheck REQUIRE AN ABN NUMBER TO GENERATE AN INVOICE? under /admin/invoice_settings/edit

> you should be able to generate (print/send) invoice


Indeed, it becomes possible to print, but:
- it is not possible to send the invoice - the red banner displayed and the invoice is not sent

So, basically, even though the checkbox is not ticked it is **not** possible to send invoices, if the ABN is **not** filled in. This is unrelated to the second business number (as I've indicated on my testing notes) -> thanks for your heads up @drummer83 :pray: 

I'll open an issue for this.

Side note: Should we consider improving the specs, for the case in which ABN mandatory is set to false?