Fixed same enterprise appear several times in the fee dropdown list
openfoodfoundation/openfoodnetwork pull request #9752
Opened 2022-10-08 13:15 UTC by maniSHarma7575

#### What? Why?
When choosing to apply fees in steps 3 and 4 of a hub's order cycle, the same enterprises was appearing several time in the drop-down list.
Closes #9603 

**Before:**
<img width="1440" alt="Screenshot 2022-10-08 at 6 15 56 PM" src="https://user-images.githubusercontent.com/39980734/194709295-127f47c9-00bd-4ac4-9869-cc7e5526e6e5.png">
<img width="1440" alt="Screenshot 2022-10-08 at 6 16 26 PM" src="https://user-images.githubusercontent.com/39980734/194709301-29a78f44-ac97-479e-9ba9-02c5ea0ab9ff.png">

**After:**

<img width="1440" alt="Screenshot 2022-10-08 at 6 17 03 PM" src="https://user-images.githubusercontent.com/39980734/194709313-fd5594c9-ae22-46f6-af6b-89af20d71447.png">
<img width="1440" alt="Screenshot 2022-10-08 at 6 40 27 PM" src="https://user-images.githubusercontent.com/39980734/194709320-c12576a3-7407-4905-a847-f45b12d926d2.png">

#### What should we test?

 - Connect to an account that has a producer-hub enterprise (with at least one available product so it can be added as a supplier)
 - Create or edit an order cycle
 - At step 2, choose the hub as the supplier, then click "Add fee"
 - See that the hub should not appears several times

#### Release notes

Changelog Category: Admin facing changes | Technical changes

The title of the pull request will be included in the release notes.

#### Dependencies

#### Documentation updates

2022-10-08 17:40 UTC, maniSHarma7575 commented
@audez @sigmundpetersen PR is ready for review.

2022-10-10 06:02 UTC, mkllnk approved these changes
Nice, thank you.

We may get rid of jQuery one day but we can update this code then. Great work.

2022-10-10 07:51 UTC, jibees requested changes
Thanks for this one!

I think I'd prefer that not use jQuery, and that's why I've made a proposal with `Set()`. I'm ok with a `filter()` method on the array also! (something like `list.filter((x, i, a) => a.indexOf(x) === i)`)

2022-10-10 07:51 UTC, jibees commented on app/assets/javascripts/admin/order_cycles/controllers/order_cycle_exchanges_controller.js.coffee
> +      $scope.enterprises[id] for id in jQuery.unique([OrderCycle.participatingEnterpriseIds()..., [OrderCycle.order_cycle.coordinator_id]...].sort()) when $scope.enterpriseFeesForEnterprise(id).lengt
I'd prefer to use jQuery.

Why not using the `Set` type: 

```diff
diff --git a/app/assets/javascripts/admin/order_cycles/controllers/order_cycle_exchanges_controller.js.coffee b/app/assets/javascripts/admin/order_cycles/controllers/order_cycle_exchanges_controller.js.coffee
index 185d5009d..ee7c1aa5c 100644
--- a/app/assets/javascripts/admin/order_cycles/controllers/order_cycle_exchanges_controller.js.coffee
+++ b/app/assets/javascripts/admin/order_cycles/controllers/order_cycle_exchanges_controller.js.coffee
@@ -18,7 +18,8 @@ angular.module('admin.orderCycles')
       OrderCycle.exchangeDirection(exchange)
 
     $scope.enterprisesWithFees = ->
-      $scope.enterprises[id] for id in jQuery.unique([OrderCycle.participatingEnterpriseIds()..., [OrderCycle.order_cycle.coordinator_id]...].sort()) when $scope.enterpriseFeesForEnterprise(id).length > 0
+      ids = [OrderCycle.participatingEnterpriseIds()..., [OrderCycle.order_cycle.coordinator_id]...]
+      $scope.enterprises[id] for id in Array.from(new Set(ids)) when $scope.enterpriseFeesForEnterprise(id).length > 0
 
     $scope.removeExchange = ($event, exchange) ->
       $event.preventDefault()
```

2022-10-10 07:51 UTC, jibees commented on app/assets/javascripts/admin/order_cycles/services/order_cycle.js.coffee
>        jQuery.unique(suppliers.concat(distributors)).sort()
Probably out of scope, but as we are modifying the file...

```diff
diff --git a/app/assets/javascripts/admin/order_cycles/services/order_cycle.js.coffee b/app/assets/javascripts/admin/order_cycles/services/order_cycle.js.coffee
index 10c624975..88ad9da1b 100644
--- a/app/assets/javascripts/admin/order_cycles/services/order_cycle.js.coffee
+++ b/app/assets/javascripts/admin/order_cycles/services/order_cycle.js.coffee
@@ -95,7 +95,7 @@ angular.module('admin.orderCycles').factory 'OrderCycle', ($resource, $window, $
     participatingEnterpriseIds: ->
       suppliers = (parseInt(exchange.enterprise_id) for exchange in this.order_cycle.incoming_exchanges)
       distributors = (parseInt(exchange.enterprise_id) for exchange in this.order_cycle.outgoing_exchanges)
-      jQuery.unique(suppliers.concat(distributors)).sort()
+      Array.from(new Set([suppliers..., distributors...]))
 
     exchangesByDirection: (direction) ->
       if direction == 'incoming'
```

2022-10-10 07:51 UTC, jibees commented on app/assets/javascripts/admin/order_cycles/controllers/order_cycle_exchanges_controller.js.coffee
> +      $scope.enterprises[id] for id in jQuery.unique([OrderCycle.participatingEnterpriseIds()..., [OrderCycle.order_cycle.coordinator_id]...].sort()) when $scope.enterpriseFeesForEnterprise(id).lengt
I'm also wondering the role of the `sort()` method. Why would we sort by id?

2022-10-10 07:51 UTC, jibees commented on app/assets/javascripts/admin/order_cycles/services/order_cycle.js.coffee
>        jQuery.unique(suppliers.concat(distributors)).sort()
(same question here around the `sort()` method ...)

2022-10-10 09:03 UTC, maniSHarma7575 commented
@jibees Feedbacks done!

2022-10-10 09:38 UTC, jibees approved these changes
Nice, thanks!

2022-10-10 16:17 UTC, drummer83 commented
Hi @maniSHarma7575,
Thank you for this pull request! :fire: 

I have tested the behavior before and after staging your pull request.

**Before:**
![Peek 2022-10-10 17-45](https://user-images.githubusercontent.com/1790176/194910764-afff12ed-fdf4-4df4-b796-d84ab8e38f46.gif)

**After:**
![Peek 2022-10-10 18-12](https://user-images.githubusercontent.com/1790176/194910777-b78aaf89-0646-41f5-b861-261c7a956627.gif)

As you can see, the enterprise is only appearing once with you pull request! Awesome!
I did not find any problems around this solution. This is ready to go! :rocket: 

Thanks again for this great contribution!

2022-10-10 22:41 UTC, merged

2022-10-11 06:47 UTC, maniSHarma7575 commented
Thanks @drummer83 @mkllnk @jibees For merging this. Happy to be part of it!