fix payment/shipping methods loading on multi-distributor order cycle checkout page
openfoodfoundation/openfoodnetwork pull request #9929
Opened 2022-11-03 07:35 UTC by abdellani

#### What? Why?

- Closes #9873

#### What should we test?

- described on #9873

#### Release notes

Changelog Category: User facing changes | Technical changes

The title of the pull request will be included in the release notes.

#### Dependencies

#### Documentation updates

2022-11-25 00:09 UTC, dacook requested changes
This looks like a good fix, however it's not covered by a spec to prove it. 

Can you please add a spec to cover this condition? I find it surprisingly satisfying and helpful to follow this order:
1. build the failing spec to show the bug (**red**),
2. apply the fix to see it pass (**green**).

I notice that this code requires up to two DB queries (first to build a list of IDs, then another to get the filtered payment methods). After adding the spec, perhaps we can try to

3. update it to use only one query (**refactor**)

2022-12-08 08:27 UTC, jibees approved these changes
Very close to https://github.com/openfoodfoundation/openfoodnetwork/pull/10076, so I'll be approve this one too!

2022-12-08 08:27 UTC, jibees commented on app/services/order_available_payment_methods.rb
> +      .select(:payment_method_id)
```suggestion
    order_cycle.distributor_payment_methods
      .where(distributor_id: distributor.id)
      .select(:payment_method_id)
```

2022-12-09 03:32 UTC, dacook commented
> For the optimization, I'm not sure how can I do it in one query. Can you please guide me?

Sorry I didn't get back to you this time, Mohamed. Thanks for pushing this forward anyway.

2022-12-15 17:04 UTC, filipefurtad0 commented
Continuing the testing notes from here:

Checking out on Shop A (/payments)

![image](https://user-images.githubusercontent.com/49817236/207922635-11ba26c4-bd2d-48b2-b924-432cc16c11e5.png)

Checking out on Shop B (/payments)

![image](https://user-images.githubusercontent.com/49817236/207922663-616e5a2d-782a-41e0-8b0e-6a1a44bc68f5.png)

We can see that only the payment method enabled for a given shop is appearing on checkout, for the customer.

Merging!

2022-12-15 17:05 UTC, merged